### ISSUE TITLE
怎么获取二维码的enc

### ISSUE THREAD

**Issue by truthNihilism** [cxOrz/chaoxing-sign-cli#100]
扫描二维码会直接跳转到学习通，找不到那串代码

**Comment by cxOrz** [comment]
那是因为好多软件，比如微信、qq，检测到识别出来的是个URL就会自动跳转到那里。我们需要的是url里面的enc参数，换个识别软件就好了，或者他既然跳转了，那就在浏览器打开，看一下地址栏，就能找到enc参数了

**Comment by truthNihilism** [comment]
已经解决，十分感谢大佬。
