### ISSUE TITLE
Dockerfile 编写错误导致镜像无法编译

### ISSUE THREAD

**Issue by killlowkey** [cxOrz/chaoxing-sign-cli#103]
编译镜像时，出现如下错误
> docker 工作空间中缺失 tsconfig.json 配置导致 yarn build 命令执行失败，就算是有  tsconfig.json 也会失败，因为工作空间中没有源代码，然后执行 tsc 将代码转换 js，最后转了个寂寞

![Snipaste_2022-10-17_12-36-46](https://user-images.githubusercontent.com/41176828/196091929-cb2b635a-b464-47db-bfc4-e59cb5447d62.png)
将 Dockerfile 修改如下，编译通过
```Dockerfile
# syntax=docker/dockerfile:1

FROM node:16-alpine

WORKDIR /app

COPY . .

RUN corepack enable && yarn && yarn build

EXPOSE 5000

CMD [ "node", "build/serve.js" ]
```

**Comment by cxOrz** [comment]
已改 😍
