### ISSUE TITLE
怎么样删除一个账户信息呢大佬

### ISSUE THREAD

**Issue by ttthhhhnmmmm** [cxOrz/chaoxing-sign-cli#105]

**Comment by cxOrz** [comment]
storage.json里，删除你不要的那个手机号的那块对象，用 {} 包裹的，一整个删掉，包括花括号

**Comment by ttthhhhnmmmm** [comment]
里面什么都没有
![image](https://user-images.githubusercontent.com/112688590/197110816-8945225e-7443-4763-b60e-7494f8400c38.png)

**Comment by cxOrz** [comment]
说明没保存任何信息

**Comment by cxOrz** [comment]
就没得删了

**Comment by ttthhhhnmmmm** [comment]
![image](https://user-images.githubusercontent.com/112688590/197111198-fe11915e-ba04-4fbc-b305-431d270cc91d.png)
这么多呀

**Comment by cxOrz** [comment]
构建的代码没同步，`yarn build` 一下

**Comment by ttthhhhnmmmm** [comment]
![image](https://user-images.githubusercontent.com/112688590/197111678-c47c4d19-294e-470d-8a70-885a984b2b21.png)
构建了一下用户全没 了

**Comment by cxOrz** [comment]
这下就同步了，重新添加吧。storage.json有两份，一份是源码里的，另一份是构建好的代码里的。根据情况修改，假如是在开发模式下，修改src里的，如果在非开发模式运行的，修改build目录里的

**Comment by ttthhhhnmmmm** [comment]
好的，谢谢
