### ISSUE TITLE
通过扫描二维码获取enc错误

### ISSUE THREAD

**Issue by moxiaowk** [cxOrz/chaoxing-sign-cli#106]
目前学习通的二维码链接为以下格式

https://passport2.chaoxing.com/mlogin?newversion=true&refer=http%3A%2F%2Fmobilelearn.chaoxing.com%3A80%2Fwidget%2Fsign%2Fe%3Fid%3D7000047728304%26c%3DGGTB65%26enc%3D00CEB0BF304117073F223D96346B2162%26DB_STRATEGY%3DPRIMARY_KEY%26STRATEGY_PARA%3Did

enc应该为enc%3D至%26D之间的部分，现在识别的%3D?扫码提取的结果为id，是最后一个%3D后面的数，可以修复一下识别获取enc的逻辑😎

![IMG_20221021_141929](https://user-images.githubusercontent.com/62387130/197126390-f3841b4f-f2fb-4fb7-92fa-a213665e0117.jpg)

**Comment by cxOrz** [comment]
这个问题似乎很久以前就修复了。是不是你的代码没更新

**Comment by moxiaowk** [comment]
😂我看看

**Comment by moxiaowk** [comment]
更新了依旧如此😂

**Comment by cxOrz** [comment]
怪，我这一切正常

**Comment by cxOrz** [comment]
更新完有没有重新 build

**Comment by moxiaowk** [comment]
找到原因了，是之前改了dist的index文件，更新后我直接拿旧文件覆盖了，就没有生效😂
