### ISSUE TITLE
yarn build 报错

### ISSUE THREAD

**Issue by Jikexiaobai** [cxOrz/chaoxing-sign-cli#109]
node版本为v16.14.0

报错信息如下：
error TS2688: Cannot find type definition file for 'node'.
  The file is in the program because:
    Entry point of type library 'node' specified in compilerOptions

  tsconfig.json:29:7
    29       "node"
             ~~~~~~
    File is entry point of type library specified here.

tsconfig.json:3:14 - error TS6053: File 'ts-node/node16/tsconfig.json' not found.

3   "extends": "ts-node/node16/tsconfig.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 2 errors in the same file, starting at: tsconfig.json:3

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

![image](https://user-images.githubusercontent.com/49304819/199555086-a29b4526-fc88-4391-b395-2e95b5190c6d.png)

**Comment by cxOrz** [comment]
装依赖了没

**Comment by Jikexiaobai** [comment]
抱歉，刚才没有看懂说明，忘记撞依赖了，现在懂了，谢谢大佬
