### ISSUE TITLE
关于挂载多个账号问题

### ISSUE THREAD

**Issue by Jackyfi** [cxOrz/chaoxing-sign-cli#111]
大佬你好，想请教一下，使用node监听如何实现同时挂载多个监听，我参考了你监听那部分代码，但是我调用多次貌似会被覆盖掉，只能监听到最后一次创建的监听

**Comment by Jackyfi** [comment]
我将代码同步执行后，在添加第二个监听的时候，发现并没有添加上，也没有任何报错。
下面是开启监听的代码，麻烦大佬帮忙看看
`const cxIM = (uf,_d,_uid,vc3,uname)=>{
 return new Promise(resolve=>{
    let WebSocket = require('ws')   
    let JSDOM = new jsdom.JSDOM('', { url: 'https://im.chaoxing.com/webim/me' });
    globalThis.window = JSDOM.window;
    globalThis.WebSocket= WebSocket;
    globalThis.navigator = JSDOM.window.navigator;
    globalThis.location = JSDOM.window.location;
    let webIM = require('../websdk3.1.4').default;
    const WebIMConfig = {
        xmppURL: "https://im-api-vip6-v2.easecdn.com/ws",
        apiURL: "https://a1-vip6.easecdn.com",
        appkey: 'cx-dev#cxstudy',
        Host: "easemob.com",
        https: true,
        isHttpDNS: false,
        isMultiLoginSessions: true,
        isAutoLogin: true,
        isWindowSDK: false,
        isSandBox: false,
        isDebug: false,
        autoReconnectNumMax: 2,
        autoReconnectInterval: 2,
        isWebRTC: false,
        heartBeatWait: 4500,
        delivery: false,
      };
      
      let conn1 = new webIM.connection({
        isMultiLoginSessions: WebIMConfig.isMultiLoginSessions,
        https: WebIMConfig.https,
        url: WebIMConfig.xmppURL,
        apiUrl: WebIMConfig.apiURL,
        isAutoLogin: WebIMConfig.isAutoLogin,
        heartBeatWait: WebIMConfig.heartBeatWait,
        autoReconnectNumMax: WebIMConfig.autoReconnectNumMax,
        autoReconnectInterval: WebIMConfig.autoReconnectInterval,
        appKey: WebIMConfig.appkey,
        isHttpDNS: WebIMConfig.isHttpDNS
      });
    
      cxApi.getIMParams(uf,_d,_uid,vc3).then(resp=>{
        conn1.open({
            apiUrl: WebIMConfig.apiURL,
            user: resp.myTuid,
            accessToken: resp.myToken,
            appKey: WebIMConfig.appkey
          });

          conn1.listen({
            onOpened : function(message) { // 连接成功回调
                console.log(uname,'成功', message);
                resolve("111");
            },
            onClosed : function(message) {
                console.log(message+"连接 已经关闭");
            }, // 连接关闭回调handleTextMessage
            onTextMessage : function(message) {
                console.log(message);
                if(message?.ext?.attachment?.att_chat_course){
                    console.log(uname ,"当前为活动消息");
                }
                else{console.log(uname, "当前为其他消息");}
            },// 收到文本消息
            onOnline : function() {
                //loginByToken(evenName, evenToken);
                console.log(uname+"已上线");
            }, // 本机网络连接成功
            onOffline : function() {
                console.log(uname+"网络断线");
                //loginByToken(evenName, evenToken);
            }, // 本机网络掉线
            onError : function(message) {
                //loginByToken(evenName, evenToken);
                console.log('连接失败', message);
            }
            })
            
    })
})

}`

**Comment by Jackyfi** [comment]
我将代码同步执行后，在添加第二个监听的时候，发现并没有添加上，也没有任何报错。
下面是开启监听的代码，麻烦大佬帮忙看看
`
const cxIM = (uf,_d,_uid,vc3,uname)=>{
 return new Promise(resolve=>{
    let WebSocket = require('ws')   
    let JSDOM = new jsdom.JSDOM('', { url: 'https://im.chaoxing.com/webim/me' });
    globalThis.window = JSDOM.window;
    globalThis.WebSocket= WebSocket;
    globalThis.navigator = JSDOM.window.navigator;
    globalThis.location = JSDOM.window.location;
    let webIM = require('../websdk3.1.4').default;
    const WebIMConfig = {
        xmppURL: "https://im-api-vip6-v2.easecdn.com/ws",
        apiURL: "https://a1-vip6.easecdn.com",
        appkey: 'cx-dev#cxstudy',
        Host: "easemob.com",
        https: true,
        isHttpDNS: false,
        isMultiLoginSessions: true,
        isAutoLogin: true,
        isWindowSDK: false,
        isSandBox: false,
        isDebug: false,
        autoReconnectNumMax: 2,
        autoReconnectInterval: 2,
        isWebRTC: false,
        heartBeatWait: 4500,
        delivery: false,
      };
      
      let conn1 = new webIM.connection({
        isMultiLoginSessions: WebIMConfig.isMultiLoginSessions,
        https: WebIMConfig.https,
        url: WebIMConfig.xmppURL,
        apiUrl: WebIMConfig.apiURL,
        isAutoLogin: WebIMConfig.isAutoLogin,
        heartBeatWait: WebIMConfig.heartBeatWait,
        autoReconnectNumMax: WebIMConfig.autoReconnectNumMax,
        autoReconnectInterval: WebIMConfig.autoReconnectInterval,
        appKey: WebIMConfig.appkey,
        isHttpDNS: WebIMConfig.isHttpDNS
      });
    
      cxApi.getIMParams(uf,_d,_uid,vc3).then(resp=>{
        conn1.open({
            apiUrl: WebIMConfig.apiURL,
            user: resp.myTuid,
            accessToken: resp.myToken,
            appKey: WebIMConfig.appkey
          });

          conn1.listen({
            onOpened : function(message) { // 连接成功回调
                console.log(uname,'成功', message);
                resolve("111");
            },
            onClosed : function(message) {
                console.log(message+"连接 已经关闭");
            }, // 连接关闭回调handleTextMessage
            onTextMessage : function(message) {
                console.log(message);
                if(message?.ext?.attachment?.att_chat_course){
                    console.log(uname ,"当前为活动消息");
                }
                else{console.log(uname, "当前为其他消息");}
            },// 收到文本消息
            onOnline : function() {
                //loginByToken(evenName, evenToken);
                console.log(uname+"已上线");
            }, // 本机网络连接成功
            onOffline : function() {
                console.log(uname+"网络断线");
                //loginByToken(evenName, evenToken);
            }, // 本机网络掉线
            onError : function(message) {
                //loginByToken(evenName, evenToken);
                console.log('连接失败', message);
            }
            })
            
    })
})
`

**Comment by cxOrz** [comment]
看起来没什么问题，你是调用接口来挂载多个的话，是可以的，一个监听对应一个子线程。

运行命令来启动多个监听，用GNU screen 吧。

代码看起来没什么问题

**Comment by Jackyfi** [comment]
我看你前面的服务代码中，是启用了一个子进程对应一个监听，会不会是这个原因

**Comment by cxOrz** [comment]
是的，也有可能
