### ISSUE TITLE
不同同浏览器访问，数据不一样

### ISSUE THREAD

**Issue by Jikexiaobai** [cxOrz/chaoxing-sign-cli#112]
测试在浏览器A添加了用户A和用户B之后 用浏览器B访问前端没有渲染出用户A和B的卡片

接着在浏览器B添加了用户C之后 用浏览器A访问 只有用户A和B没有渲染出用户C的卡片 而浏览器B访问有C
然后使用浏览器C访问前端，没有用户A、B、C的卡片。

想知道是根据什么判断的，标识 还是 cookie 或者其它的 不是很清楚，想请教大佬

**Comment by cxOrz** [comment]
数据都存在indexeddb里。想象一下，你在电脑的chrome 里登录了百度账号，那在edge 里访问百度肯定没登录，他俩不是一个浏览器，数据都不存在一起，完全独立的两个东西。

**Comment by cxOrz** [comment]
在哪个浏览器登陆，就只能在那个浏览器看到。

**Comment by Jikexiaobai** [comment]
好的，谢谢大佬，了解了
