### ISSUE TITLE
只能通过ui启动一个账号的监听

### ISSUE THREAD

**Issue by huluii** [cxOrz/chaoxing-sign-cli#113]
在 yarn monitor后运行serve，但在ui界面只能启动最开始录入账号的监听

**Comment by cxOrz** [comment]
当然，防止别人未经允许使用。

https://github.com/cxOrz/chaoxing-sign-cli/issues/95#issuecomment-1270440814

**Comment by 9527-bit** [comment]
> 当然，防止别人未经允许使用。
> 
> [#95 (comment)](https://github.com/cxOrz/chaoxing-sign-cli/issues/95#issuecomment-1270440814)

本人是docker部署的，现在随便一个用户都能在ui界面启动监听了，所以现在是去掉了这个功能吗？

**Comment by cxOrz** [comment]
是的
