### ISSUE TITLE
手动签到无法获取课程

### ISSUE THREAD

**Issue by ANYANshutdown** [cxOrz/chaoxing-sign-cli#114]
在使用UI或者yarn start进行手动签到时，返回结果为“无课程”，监听模式正常签到。

**Comment by cxOrz** [comment]
手动签到检查的都是加入的课程签到，如果没加入课程，就扫不到。

监听模式监听的是课程和群聊，没课程但有群聊签到，是可以签的。

**Comment by ANYANshutdown** [comment]
不好意思，可能是我的表述有误，在我自行部署在腾讯云上面的web端点击“开始”获取到的返回值始终是NoCourse，而对比你的演示网站，上面是NoActivity。两者均为同一个账号，以及同一个时间点。

**Comment by cxOrz** [comment]
我的网站，是长久不更新的，只给个样子看看，一切以自己用最新代码部署的为准

**Comment by ANYANshutdown** [comment]
不好意思，我发现问题了，是腾讯云的问题，对于来自腾讯云的ip对于超星部分的资源是不允许访问的
