### ISSUE TITLE
更新Dockerfile

### ISSUE THREAD

**Issue by accors** [cxOrz/chaoxing-sign-cli#122]
参考Turbo官方示例：https://github.com/vercel/turbo/blob/dd85f00f8efc6bd2c78f6b0106a0e409992d6141/examples/with-docker/apps/api/Dockerfile
Turbo在alpine基础的docker容器内正常运行需要安装libc6-compat。
切换pnpm后，需要将yarn改为pnpm，否则镜像会打包失败，同时package.json内写明了node>=18，应将镜像基础改为node:lts-alpine。

**Comment by cxOrz** [comment]
我这暂时没docker环境，不嫌麻烦的话可以按照你说的改一下，测试一下是否能构建成功，完事发起个pr我合并 😘 。或者回头我在装上 docker 搞~

**Comment by accors** [comment]
我直接发PR吧，我在Ubuntu 22.04上测试这样可以正常运行。

**Comment by cxOrz** [comment]
OK 感谢
