### ISSUE TITLE
Ubuntu22.04 Not Working with `npm start` via QRCode

### ISSUE THREAD

**Issue by danielhu19** [cxOrz/chaoxing-sign-cli#124]
其他方式都可以用，但是`npm start`无法检测到任何签到(不仅是二维码)
![image](https://user-images.githubusercontent.com/86143910/222465437-27e56e00-8d3d-4206-a1c8-7cd1d7841107.png)

已进行的解决方式：
- upgrade `npm` and rebuild 
- read other closed issues
- retry, retry and retry...

Thanks!

**Comment by cxOrz** [comment]
是正常的
![image](https://user-images.githubusercontent.com/32982052/222468847-667c9bff-aa7c-4d97-a57a-148495f9b048.png)

**Comment by cxOrz** [comment]
你的签到是群聊签到，还是在某个课程下的签到。
如果是纯群聊签到，只能用监听来检测到，如果是某个课程下的，那就是都可以用

**Comment by danielhu19** [comment]
> 你的签到是群聊签到，还是在某个课程下的签到。 如果是纯群聊签到，只能用监听来检测到，如果是某个课程下的，那就是都可以用

班级签到不可以吗？

**Comment by cxOrz** [comment]
> > 你的签到是群聊签到，还是在某个课程下的签到。 如果是纯群聊签到，只能用监听来检测到，如果是某个课程下的，那就是都可以用
> 
> 班级签到不可以吗？

没有课程的话是没有办法手动检测的，只能靠监听

**Comment by danielhu19** [comment]
Thanks. (I'd like to reopen it if not working.)
