### ISSUE TITLE
本地web项目 点击监听按钮并没有进入监听状态

### ISSUE THREAD

**Issue by Mrkk1** [cxOrz/chaoxing-sign-cli#125]
在根目录 pnpm serve：启动前端页面、运行后端接口，登录成功后无法进行监听，点击监听按钮并没有进入监听状态。

**Comment by cxOrz** [comment]
![Screenshot_20230303-103359_Chrome](https://user-images.githubusercontent.com/32982052/222617025-590062fd-be5c-4e63-b341-6778f09263a1.png)

**Comment by Mrkk1** [comment]
按照您的方案我已经将项目跑起来了，遗憾的是我并没有看到在readme中提及到的二维码签到界面的进入按钮 亦或是提交enc参数的输入框

**Comment by cxOrz** [comment]
如果是纯群聊，签到只能监听来检测到，监听模式没办法签二维码。如果是课程下的签到，可以手动检测到，出现输入框让填enc。

**Comment by Mrkk1** [comment]
感谢您的回复，我已经理解了 我将 关闭这个issue
