### ISSUE TITLE
按’确认添加‘按钮无反应

### ISSUE THREAD

**Issue by wu695208428** [cxOrz/chaoxing-sign-cli#126]
服务端：
server:serve: API Server: http://localhost:5000
server:serve:
server:serve:   SyntaxError: Unexpected token < in JSON at position 0
server:serve:       at JSON.parse (<anonymous>)
server:serve:       at userLogin (C:\Users\Administrator\Desktop\chaoxing-sign-cli-main\apps\server\build\functions\user.js:39:14)
server:serve:       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
server:serve:       at async C:\Users\Administrator\Desktop\chaoxing-sign-cli-main\apps\server\build\serve.js:30:18
server:serve:       at async C:\Users\Administrator\Desktop\chaoxing-sign-cli-main\apps\server\build\serve.js:291:5
server:serve:       at async C:\Users\Administrator\Desktop\chaoxing-sign-cli-main\apps\server\build\serve.js:284:5
server:serve:       at async bodyParser (C:\Users\Administrator\Desktop\chaoxing-sign-cli-main\node_modules\.pnpm\koa-bodyparser@4.3.0\node_modules\koa-bodyparser\index.js:95:5)
server:serve:

web端：
Request URL: http://xx.xxx.xxx.xx:5000/login
Request Method: POST
Status Code: 500 Internal Server Error
Referrer Policy: strict-origin-when-cross-origin

C:\Users\Administrator>node -v
v18.14.2
服务器防火墙已开放端口， baseUrl也改了

**Comment by cxOrz** [comment]
过一段时间再试一下吧，这个是登陆失败了，可能是ip异常。拿不到登录结果

**Comment by wu695208428** [comment]
> 过一段时间再试一下吧，这个是登陆失败了，可能是ip异常。拿不到登录结果

好的，谢谢😂

**Comment by wu695208428** [comment]
实测阿里云登录302/403，超星可能检测云服务器
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>tengine</center>
</body>
</html>
```

**Comment by cxOrz** [comment]
试一下百度云，就挺好用

**Comment by cxOrz** [comment]
关联 #133
