### ISSUE TITLE
版本4.10：使用pnpm start 运行手动签到功能会出现用户名错误

### ISSUE THREAD

**Issue by hellc123** [cxOrz/chaoxing-sign-cli#127]
作者你好，在使用 pnpm start 运行手动签到功能时，用户名会显示成签到名。
在使用 pnpm monitor 运行监控模式和使用 pnpm server 启动前端页面时，没有出现该问题。
感谢作者和所有贡献者

**Comment by cxOrz** [comment]
![image](https://user-images.githubusercontent.com/32982052/223114129-c55a559a-abaa-49ba-b913-b15ed72fd4bf.png)

截个图看看，我这用户名还是挺正常的

**Comment by hellc123** [comment]
用户名为小李：
![image](https://user-images.githubusercontent.com/47733547/223131334-7091185c-1b58-4cee-9ddf-a51e541b755d.png)
在手动签到后，在教师端会显示成设置的签到标题(正常应该显示为小李)：
![image](https://user-images.githubusercontent.com/47733547/223131769-41b130e1-63c9-43f3-961b-b7bfbae2a7dc.png)

**Comment by cxOrz** [comment]
已修复

**Comment by hellc123** [comment]
感谢！
