### ISSUE TITLE
可以弄在服务器上面吗

### ISSUE THREAD

**Issue by openai8** [cxOrz/chaoxing-sign-cli#128]
青龙面板那种

**Comment by cxOrz** [comment]
没用过这类面板。ssh连上直接用命令就行

**Comment by 2280114152** [comment]
> > 青龙面板那种
> 
> 
> 青龙面板是定时任务面板 这个项目是24h监听的 这两个项目没有关联

你24小时监听？你不怕出问题吗？到时间运行不更稳定吗，作者都说了监听模式，不能挂着不关

**Comment by AAlieZZ** [comment]
> > > > 青龙面板那种
> > > 
> > > 
> > > 青龙面板是定时任务面板 这个项目是24h监听的 这两个项目没有关联
> > 
> > 
> > 你24小时监听？你不怕出问题吗？到时间运行不更稳定吗，作者都说了监听模式，不能挂着不关
> 
> 超星风控并不严 用cron定时 写一个约二十行交互sh即可 自己看着改 大概就这样
> 
> ```
> 
> #!/bin/bash
> #第一步要先用cd命令 进入到你项目
> # 将脚本添加至 cron 定时任务中
> (crontab -l ; echo "* * * * * /~/auto_monitor.sh") | crontab -
> 
> # 执行pnpm monitor命令
> echo "执行pnpm monitor命令..."
> pnpm monitor &
> 
> # 等待3秒，确保pnpm monitor命令已启动
> sleep 3
> 
> # 向下滚动一次并回车
> echo "向下浏览一次并回车..."
> echo -ne "\033[B\r" | sleep 1
> 
> # 输入y并回车
> echo "输入y并回车..."
> echo "y" | sleep 1
> 
> # 等待7200秒后关闭脚本
> echo "等待7200秒后关闭脚本..."
> sleep 7200
> 
> # 关闭pnpm monitor命令
> echo "关闭pnpm monitor命令..."
> killall pnpm
> 
> # 关闭脚本
> echo "脚本执行完毕，即将关闭..."
> kill $$
> ```

这个脚本似乎会卡在登录那里……

**Comment by cxOrz** [comment]
这里代码是选择你的账号，卡住的话是不是因为没登陆过账号？
所以向下选择，选的是手动添加，就卡住了。
```bash
# 向下滚动一次并回车
echo "向下浏览一次并回车..."
echo -ne "\033[B\r" | sleep 1
```

**Comment by AAlieZZ** [comment]
> 这里代码是选择你的账号，卡住的话是不是因为没登陆过账号？ 所以向下选择，选的是手动添加，就卡住了。
> 
> ```shell
> # 向下滚动一次并回车
> echo "向下浏览一次并回车..."
> echo -ne "\033[B\r" | sleep 1
> ```

噢不好意思，我这里第一个选项才是已登录的账号
```
? 选择用户 › - Use arrow-keys. Return to submit.
❯   16620415680
    手动登录
```

**Comment by AAlieZZ** [comment]
我试了下可以用 expect 脚本
```
#!/usr/bin/expect

# 第一步要先用cd命令 进入到你项目
cd /path/to/chaoxing-sign-cli

# 执行pnpm monitor命令
spawn pnpm monitor
# 等待3秒，确保pnpm monitor命令已启动
sleep 3
# 回车
send "\r"
sleep 1
send "\r"
# 等待7200秒后关闭脚本
sleep 7200
# 关闭pnpm monitor命令
send \x03
```
