### ISSUE TITLE
build了web和serever之后，将dist部署在Nginx后可以访问前端，但是后端起不来了，先启动后端服务，后部署前端，访问web页面显示的是后端API服务

### ISSUE THREAD

**Issue by Aspirin2002** [cxOrz/chaoxing-sign-cli#131]
如题：build了web和serever之后，将dist部署在Nginx后可以访问前端，但是后端起不来了（pnpm serve 显示端口占用，此时monitor正常使用），
![image](https://user-images.githubusercontent.com/70762156/223500871-4f98eff7-f0cb-4190-8254-85468ffd7ce1.png)

先启动后端服务，然后部署前端，访问web页面显示的是后端API服务
![image](https://user-images.githubusercontent.com/70762156/223500346-7990376c-da0d-4184-968b-7c29726c58b3.png)

这个是什么情况 望解答

**Comment by cxOrz** [comment]
Nginx 托管了静态页面就占了个80端口，接口默认是5000端口，不会被占用。
先部署后部署哪个没有区别，接口默认通过ip:5000访问，页面直接ip就访问到了

**Comment by Aspirin2002** [comment]
> Nginx 托管了静态页面就占了个80端口，接口默认是5000端口，不会被占用。 先部署后部署哪个没有区别，接口默认通过ip:5000访问，页面直接ip就访问到了

还有个问题，调用了腾讯云ocr之后，在腾讯云显示调用成功，但是网站填写enc参数失败，一直在转圈
![image](https://user-images.githubusercontent.com/70762156/223622949-8de48b98-6802-485f-b493-14a187dcb179.png)
![image](https://user-images.githubusercontent.com/70762156/223622959-055fcae5-b6f9-46ae-b4ff-183a3868aac8.png)

**Comment by cxOrz** [comment]
这得看看f12网络请求，是什么情况
