### ISSUE TITLE
Docker部署后无法访问API端口

### ISSUE THREAD

**Issue by QLozin** [cxOrz/chaoxing-sign-cli#133]
在云服务器中部署
使用
`docker run --name chaoxing -p 5000:5000 gh....`
拉起镜像后，再使用Nginx Docker进行反代理，反代理大致如下：
`listen 443 ssl;`
`server_name example.com;`
`location / {`
`proxy_pass http://超星容器的网桥IP;`
`proxy_set_header Host $host;`
`proxy_set_header X-Real-IP $remote_addr;`
`proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`
`ssl ....`
前端能正常访问但是无法登录
![](https://user-images.githubusercontent.com/53658214/224867457-1779dfdf-69ae-4921-aa3d-fb383864277f.png)
显示是登录的请求使用的是localhost:5000地址，这显然不是正确的
文档中似乎没有说明如何去修改这个，希望得到你的帮助。

**Comment by cxOrz** [comment]
![Screenshot_20230314-122015_Chrome](https://user-images.githubusercontent.com/32982052/224892523-4d73c2aa-4c1f-4efc-94a0-e6587afaec20.png)

**Comment by QLozin** [comment]
非常抱歉没有注意到相关表述
在docker内的文件地址可能不同
我尝试在docker镜像里面寻找`find / -name api.ts`
结果为
①`/app/apps/server/src/configs/api.ts`
②`/app/apps/web/src/config/api.ts`
经过查看，修改了②中的`const baseUrl = http://docker网桥中容器本身的IP : 5000`
然后重启了容器
不幸的是，他没有按预想的那样工作，前端依然尝试在`localhost`寻找API接口
我不知道是否正确修改了文件或者按照步骤去进行
希望能获得更多指导

**Comment by cxOrz** [comment]
Web页面，修改完源码，得重新构建才生效

**Comment by QLozin** [comment]
非常感谢您的回答！
我已经初步解决了问题。
唯一的缺憾在于docker容器必须将5000端口映射到宿主机才能正常运作，难以使用nginx的反代理去代理5000端口。
我的nginx关于反代理的写法如下
![图片](https://user-images.githubusercontent.com/53658214/224987561-72e52720-3a7f-440c-ad74-33dda227edc9.png)
如果您比较忙，我可以就这么用着。
感谢您的帮助！

**Comment by cxOrz** [comment]
肯定得把 5000 映射出来，不然外界访问不到。
最新 Docker 镜像里自带 Nginx，和接口一块启动的，不用在外面再配个 Nginx，直接改里面的配置文件就行，他俩都在同一个容器，配反向代理就不用 172...了，直接 localhost 应该就可以

**Comment by bujue1** [comment]
@cxOrz 您好 请问这样是什么问题呢 
![image](https://user-images.githubusercontent.com/94858092/225011168-83fccd8a-351b-49bd-aa17-ec43b529adf2.png)

**Comment by DUXING130** [comment]
> 非常感谢您的回答！ 我已经初步解决了问题并顺利使用。 唯一的缺憾在于docker容器必须将5000端口映射到宿主机才能正常运作，难以使用nginx的反代理去代理5000端口。 我的nginx关于反代理的写法如下 ![图片](https://user-images.githubusercontent.com/53658214/224987561-72e52720-3a7f-440c-ad74-33dda227edc9.png) 如果您比较忙，我可以就这么用着。 感谢您的帮助！

我能弱弱问一句你是如何在docker里重新build的嘛？是直接修改镜像然后重建容器？

**Comment by DUXING130** [comment]
> 代码重新构建完，重启容器就行了

docker拉过来的镜像可以直接重新构建？

**Comment by QLozin** [comment]
> > 非常感谢您的回答！ 我已经初步解决了问题并顺利使用。 唯一的缺憾在于docker容器必须将5000端口映射到宿主机才能正常运作，难以使用nginx的反代理去代理5000端口。 我的nginx关于反代理的写法如下 ![图片](https://user-images.githubusercontent.com/53658214/224987561-72e52720-3a7f-440c-ad74-33dda227edc9.png) 如果您比较忙，我可以就这么用着。 感谢您的帮助！
> 
> 我能弱弱问一句你是如何在docker里重新build的嘛？是直接修改镜像然后重建容器？

pnpm build等指令，在文档里有

**Comment by DUXING130** [comment]
> > > 非常感谢您的回答！ 我已经初步解决了问题并顺利使用。 唯一的缺憾在于docker容器必须将5000端口映射到宿主机才能正常运作，难以使用nginx的反代理去代理5000端口。 我的nginx关于反代理的写法如下 ![图片](https://user-images.githubusercontent.com/53658214/224987561-72e52720-3a7f-440c-ad74-33dda227edc9.png) 如果您比较忙，我可以就这么用着。 感谢您的帮助！
> > 
> > 
> > 我能弱弱问一句你是如何在docker里重新build的嘛？是直接修改镜像然后重建容器？
> 
> pnpm build等指令，在文档里有

收到

**Comment by Ta01017** [comment]
> docker attach 进容器，去里面修改、构建代码，代码在 /app 目录下。

您好，我使用docker attach进容器的时候会卡住，没反应，这是什么问题 TAT

**Comment by Ta01017** [comment]
> > > docker attach 进容器，去里面修改、构建代码，代码在 /app 目录下。
> > 
> > 
> > 您好，我使用docker attach进容器的时候会卡住，没反应，这是什么问题 TAT
> 
> 使用docker exec -it /bin/bash（有时候使用/bin/sh）试试？

好的好的

**Comment by cxOrz** [comment]
关于 Docker 镜像的使用说明，请参考 [DockerGuide](../blob/main/DockerGuide.md)，感谢 @QLozin 的文档

**Comment by wzed123** [comment]
![image](https://github.com/cxOrz/chaoxing-sign-cli/assets/91612072/60465602-3fa3-4fd5-b574-4e85ed711fb2)
哥，这种的只能在终端运行，如何让他自动运行

**Comment by wzed123** [comment]
> > ![图像](https://user-images.githubusercontent.com/91612072/273229973-60465602-3fa3-4fd5-b574-4e85ed711fb2.png)哥，这种的终端只能在运行，如何让他自动运行> > ![图像](https://user-images.githubusercontent.com/91612072/273229973-60465602-3fa3-4fd5-b574-4e85ed711fb2.png)哥，这种的终端只能在运行，如何让他自动运行>> docker部署后他就在容器里运行了，不清楚你所说的“自动运行”意味着什么，我也很少使用1Panel `NEED MORE INFO`>> docker部署后他就在容器里运行了，不清楚你所说的“自动运行”意味着什么，我也很少使用1Panel `NEED MORE INFO`就是我运行docker的时候，他这个签到也运行着，不要我手动输入监听端口了

**Comment by wzed123** [comment]
![}V MG OMZ((B5_KCWESQ%X3](https://github.com/cxOrz/chaoxing-sign-cli/assets/91612072/cac2df79-f77e-47fa-8d08-9c008c1ee7cf)
哥，您好这种打卡的他要终端输入命令每次都要启动。我想让他容器启动，他这个脚本也跟着启动就不要我去终端输入命令了

**Comment by cxOrz** [comment]
容器启动之后，不需要进入命令行运行什么东西。直接通过 域名/IP:端口 访问页面就行了。

**Comment by wzed123** [comment]
哥，我看日志是这种的，他这个localhost跑不起来，我ip直接加进去了，也不行，显示无法访问



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cxOrz/chaoxing-sign-cli"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月7日(星期六) 中午12:33
***@***.***&gt;;
抄送:&nbsp;"Dust ***@***.******@***.***&gt;;
主题:&nbsp;Re: [cxOrz/chaoxing-sign-cli] Docker部署后无法访问API端口 (Issue #133)





 
容器启动之后，不需要进入命令行运行什么东西。直接通过 域名/IP:端口 访问页面就行了。
