### ISSUE TITLE
一些自动监控的问题？

### ISSUE THREAD

**Issue by yilinyo** [cxOrz/chaoxing-sign-cli#136]
使用docker 构建 api 如何 为用户添加 监听基本信息？

如果 使用 本地部署 是否可以不用每次 pnpm moniter 来构建基本信息能否在UI界面完成 监听基本信息的设置

**Comment by cxOrz** [comment]
未来有这个打算修改这个地方，目前正在春招，等我找到班上就…

**Comment by cxOrz** [comment]
更了
