### ISSUE TITLE
docker部署后无法登录账号

### ISSUE THREAD

**Issue by ZhuJD-China** [cxOrz/chaoxing-sign-cli#139]
80port出现前端UI界面无法登录
5000port出现Welcome, chaoxing-sign-cli API service is running.

**Comment by cxOrz** [comment]
https://github.com/cxOrz/chaoxing-sign-cli/issues/126#issue-1608763790

**Comment by cxOrz** [comment]
有没有把API地址改成服务器IP或者域名，不然就是localhost肯定就访问不到
