### ISSUE TITLE
安卓小米11 pnpm install失敗

### ISSUE THREAD

**Issue by JImRubbish** [cxOrz/chaoxing-sign-cli#143]
我手機成功安裝了PNPM和NODE。但是在PNPM install時，告訴我unsupported platform android arm64
請您看看有什麼解決辦法嗎？（我按照您的指示，安裝完NODE後，重啟TERMUX後嘗試安裝PNPM INSTALL的）
![IMG_20230401_133519.jpg](https://user-images.githubusercontent.com/72197605/229267710-979102dc-93ad-4e3b-8743-a6a61fa42155.jpg)

**Comment by JImRubbish** [comment]
![IMG_20230401_133519.jpg](https://user-images.githubusercontent.com/72197605/229267722-fc868b04-1a30-4686-b496-c7d12a99b2b6.jpg)

**Comment by cxOrz** [comment]
可以把 turbo 依赖移除，进入 `apps/server` 目录下运行你想要的命令，一般在 Termux 都是在这子项目里运行手动签到、监听模式，不要忘记先 build 再运行。

```bash
pnpm remove turbo
cd apps/server
# 运行你想要的命令
# ...
```

**Comment by JImRubbish** [comment]
> 可以把 turbo 依赖移除，进入 `apps/server` 目录下运行你想要的命令，一般在 Termux 都是在这子项目里运行手动签到、监听模式，不要忘记先 build 再运行。
> 
> ```bash
> pnpm remove turbo
> cd apps/server
> # 运行你想要的命令
> # ...
> ```

turbo移除後能成功install了，謝謝您
