### ISSUE TITLE
win10系統，pnpm build成功，但是pnpm start失敗。

### ISSUE THREAD

**Issue by JImRubbish** [cxOrz/chaoxing-sign-cli#145]
前面都很順利，就是最後start失敗，不知道爲什麽造成這個問題，麻煩您請再看看，謝了！
（node是Node.js v18.1.0，pnpm也安裝了）
![image](https://user-images.githubusercontent.com/72197605/229361268-1dfd0b57-45c6-4bb8-86ea-35ccafd2efc4.png)

**Comment by Hallaey** [comment]
我也出现了同样的问题，希望大大解答谢谢！

**Comment by cxOrz** [comment]
今天写的代码问题，等我解决一下

**Comment by Lingzhou-Ting** [comment]
加油，我也是这个问题

**Comment by cxOrz** [comment]
修好了 b8111ab17d4fe55e408382124d810b44050f73af

**Comment by cxOrz** [comment]
Web 页面又出问题了，解决一个又出一个...

**Comment by JImRubbish** [comment]
> 修好了 b8111ab17d4fe55e408382124d810b44050f73af

感謝大佬！
