### ISSUE TITLE
监听不可用，docker部署

### ISSUE THREAD

**Issue by ANYANshutdown** [cxOrz/chaoxing-sign-cli#147]
使用web页面填写监听信息后，使用监听显示正常，但无法进行签到
docker中使用pnpm monitor手动签到报错如下
![图片](https://user-images.githubusercontent.com/47505725/229368061-d07210e7-08f7-4f08-9132-11015323b45b.png)
/app/apps/server/build/monitor.js:383
                cq.send(`${IM_Params.myName}，检测到${(0, activity_1.getSignType)(PPTActiveInfo)}，将在${config.monitor.delay}秒后处理`, config.cqserver.target_id);
                   ^

TypeError: Cannot read properties of undefined (reading 'send')
    at e.onTextMessage (/app/apps/server/build/monitor.js:383:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.7.0
 ELIFECYCLE  Command failed with exit code 1.

**Comment by cxOrz** [comment]
感谢！又一个bug。修好了，推了，等CI构建完就行了，这几天改动太多了，要不先别用docker，直接拉代码更轻便些
