### ISSUE TITLE
部署到ECS服务器错误

### ISSUE THREAD

**Issue by QianYu13** [cxOrz/chaoxing-sign-cli#148]
![image](https://user-images.githubusercontent.com/74176788/229442033-19bde8c1-0763-494d-b8ea-50675f8ebd13.png)
先是这个，然后跳转查看后发现，哪来的39行？？
![image](https://user-images.githubusercontent.com/74176788/229442254-23e15d99-19cf-4114-84c5-03654034fd4c.png)
![image](https://user-images.githubusercontent.com/74176788/229442257-adc655a6-8d83-4db9-b8f7-86eef5527780.png)
给我干傻了

**Comment by cxOrz** [comment]
IP问题，本地可以运行吗

**Comment by QianYu13** [comment]
本地可以跑 ，但是监听报错，[就跟之前ISS的这个哥们一样的问题，但是手动没问题](https://github.com/cxOrz/chaoxing-sign-cli/issues/147#issue-1651024308)

**Comment by cxOrz** [comment]
更新代码了吗，这个已经修了

**Comment by QianYu13** [comment]
好的，辛苦了，那服务器这个是需要我fork到我的库然后把端口换成我ip地址这个意思吗

**Comment by cxOrz** [comment]
不用fork到你的库，代码拉下来，直接改代码就行

**Comment by QianYu13** [comment]
刚刚试了一下，还是报错，我觉得是我改的地方不对，我投降 XD
