### ISSUE TITLE
使用最新版UI显示Missing script start or file server.js

### ISSUE THREAD

**Issue by Q852456q** [cxOrz/chaoxing-sign-cli#149]
如题，win环境，已经安装了pnpm和nodejs18.15.0
具体报错如下：
PS E:\CHAOXING_SIGNIN\chaoxing-sign-cli\apps\web> pnpm start
 ERR_PNPM_NO_SCRIPT_OR_SERVER  Missing script start or file server.js
已经执行过build了。

**Comment by cxOrz** [comment]
![image](https://user-images.githubusercontent.com/32982052/229479231-f02ae2f3-b01a-4ad1-ac92-7d687a0d08d1.png)
![image](https://user-images.githubusercontent.com/32982052/229479370-60aa1a91-b6a6-439c-90ca-5c1d0219f16e.png)
没问题啊，还有，为什么你那里 pnpm start 会报 serverjs 的错，start 命令运行的是 index.js

**Comment by cxOrz** [comment]
看到了。在 \apps\web 下运行的 pnpm start ，这里没有 start 命令。

**Comment by cxOrz** [comment]
![image](https://user-images.githubusercontent.com/32982052/229480326-a27d3028-f15d-41a4-8173-50251c9c8a55.png)

**Comment by Q852456q** [comment]
> ![图像](https://user-images.githubusercontent.com/32982052/229480326-a27d3028-f15d-41a4-8173-50251c9c8a55.png)

明白了，感谢大佬，是我没能读明白文档，谢谢大佬
