### ISSUE TITLE
UI端显示无签到活动，后端控制台显示这样，有点诡异

### ISSUE THREAD

**Issue by DangerFickle** [cxOrz/chaoxing-sign-cli#150]
![Screenshot_20230403_181452.jpg](https://user-images.githubusercontent.com/59493932/229481117-3a72c81b-4f6a-4b64-8cbd-a1c64b4f3684.jpg)

**Comment by cxOrz** [comment]
如何复现这个情况，我试试看

**Comment by DangerFickle** [comment]
![正在上传 x2{cc1fda0} (c0d76c9b-02e8-4286-b115-748a746c3b7e id=0x7f0a03f6 tag=BaseCommentFragment)…]()

宝塔node项目配置如上，先build再serve的，然后大号发布二维码签到，小号在UI点击签到出现这个情况，其他类型签到也是这样，不知道我是不是个例

**Comment by DangerFickle** [comment]
> 如何复现这个情况，我试试看

![IMG_20230403_183733.jpg](https://user-images.githubusercontent.com/59493932/229486679-b3f31f72-d2fb-4602-9664-cc891a72da51.jpg)

宝塔node项目配置如上，先build再serve的，然后大号发布二维码签到，小号在UI点击签到出现这个情况，其他类型签到也是这样，不知道我是不是个例

**Comment by cxOrz** [comment]
更新一下代码试试看，不知道是不是因为这个问题，刚修了一个bug

**Comment by DangerFickle** [comment]
试了，还是老样子

**Comment by DangerFickle** [comment]
![Snipaste_2023-04-03_21-27-07](https://user-images.githubusercontent.com/59493932/229523742-7436efa1-2331-4f72-90ec-44e41734d89f.png)
现在控制台这样

**Comment by cxOrz** [comment]
卧槽

**Comment by DangerFickle** [comment]
> 实在没遇到过，这种情况，这个签到检测的过程中，用到了Promise.any，他是从Node15才支持的，要不你把Node升级到18试试

NodeJS升级到17.9.1，现在没问题了
