### ISSUE TITLE
UI遇到问题，修改src下config里的ts文件里的为域名后，重新build后进dev,显示的还是localhost:3000

### ISSUE THREAD

**Issue by Q852456q** [cxOrz/chaoxing-sign-cli#151]
如题，我是有公网IP做DDNS的，同时放行了端口，按照UI里的修改localhost:3000为自己的域名+端口后重新build后无效，我之前有改过一次发现不起效后就把整个删除重来了，还是没用，我在WEB下的vite.config.ts里发现了一个port5000，我不知道是干嘛用的，也不知道是啥情况，还请大佬解答，这次没有报错代码

**Comment by Q852456q** [comment]
打错了是localhost:5000

**Comment by Q852456q** [comment]
> 如题，我是有公网IP做DDNS的，同时放行了端口，按照UI里的修改localhost:3000为自己的域名+端口后重新build后无效，我之前有改过一次发现不起效后就把整个删除重来了，还是没用，我在WEB下的vite.config.ts里发现了一个port5000，我不知道是干嘛用的，也不知道是啥情况，还请大佬解答，这次没有报错代码

修改的是配置项baseUrl

**Comment by cxOrz** [comment]
静态页面应该由 dev 命令提供访问，你应该build，然后把静态网页放在Nginx下，或者使用其他的Web服务器来托管页面。这样的话，需要开放80端口（不配置SSL）和5000端口（接口服务）。

**Comment by cxOrz** [comment]
可以的，随便动

**Comment by Q852456q** [comment]
> 可以的，随便动
感谢大佬的回复，我现在有在nginx的config 里加入 
location /api/ {
        proxy_pass http://127.0.0.1:11001/;
    }
然后关于前端的设置是：
server {
        listen       11000;
        server_name  私有域名;

        location / {
            root   html/dist;
            index  index.html index.htm;
        location /api/ {
        proxy_pass http://127.0.0.1:11001/;
    }
        }
    }
前端已经可以在公网上打开了，但是登录账号信息还是没有反应...
