### ISSUE TITLE
位置签到叙述不详尽

### ISSUE THREAD

**Issue by iaqn** [cxOrz/chaoxing-sign-cli#153]
位置签到可以把详细地址上一行所显示的经纬度位置（初始默认地址）修改成你要输入的经纬度位置。具体位置是SEVER/bulid/index.js的第65行。
好处：可以直接用初始默认地址，节省时间。
improve：希望详细地址也有初始默认地址。
【问题已进行修改】

**Comment by cxOrz** [comment]
#152 
@SummonHIM @accors @conql @o0Lev1s0o @lzw-723 @yanhy2000 @QLozin @ANYANshutdown 
我不理解，xdm帮我看看是什么意思，包括 issue152 :smile:

**Comment by QLozin** [comment]
位置签到时再去坐标提取拿坐标进行签到太繁琐因此我都使用已经设置好的监听进行位置签到，我难以理解问题描述

建议该问题配上图片辅助理解🤔

**Comment by cxOrz** [comment]
> 位置签到时再去坐标提取拿坐标进行签到太繁琐因此我都使用已经设置好的监听进行位置签到，我难以理解问题描述
> 
> 建议该问题配上图片辅助理解🤔

这个确实是问题，待会更新一下，把位置签到的参数值存下来，下次使用直接默认填充上次用过的值

**Comment by cxOrz** [comment]
已在 261271dd33b79d0f96017d615360f93dea0fccfc 支持，将缓存手动签到信息，并在每次手动签到时默认填充缓存值；
