### ISSUE TITLE
Bug: 网页端监听配置页的一些问题

### ISSUE THREAD

**Issue by SummonHIM** [cxOrz/chaoxing-sign-cli#154]
1. 打开监听配置后，保存或是取消或是点击周围退出。点击添加账号后又会跳转回监听配置页。
~~2. 导入旧版本生成的`storage.json`后，若不在网页端填入相同信息。监控后控制台报错`Cannot read properties of undefined (reading 'delay')`。随即网页白屏~~ 既然都更新了。感觉这个没有什么修复的必要

**Comment by cxOrz** [comment]
这个 Cannot read properties of undefined (reading 'delay') 有没有更详细一些的错误

**Comment by cxOrz** [comment]
storage.json 建议不要导入，数据格式有时候也会改动

**Comment by SummonHIM** [comment]
> storage.json 建议不要导入，数据格式有时候也会改动

正常添加上去的就复现不回来了，应该是嗯导入storage.json的锅吧

**Comment by cxOrz** [comment]
对话框那个修过了，拉新代码即可

**Comment by SummonHIM** [comment]
> 对话框那个修过了，拉新代码即可

可以了，多谢
