### ISSUE TITLE
Docker部署完项目之后，点击登录没反应。

### ISSUE THREAD

**Issue by NewX9** [cxOrz/chaoxing-sign-cli#155]
部署完项目之后，用docker exec进入项目内修改src/config/api.ts ：该文件中配置 baseUrl 变量后，重启容器后进入前端页面，输入账号密码进行登录，依然没有反应，登陆失败或登陆成功的消息都没有，在阿里云服务器中试过，在本地也试过。都没有反应。

**Comment by cxOrz** [comment]
f12看看请求正常吗

**Comment by cxOrz** [comment]
修改完代码，也没有重新构建使之生效呢

**Comment by NewX9** [comment]
我是直接重启的容器，好像没有效果，刚刚用F12查，请求的还是http://localhost:5000/login这个地址。

**Comment by cxOrz** [comment]
那肯定的啊，修改了源文件，却没有按照修改后的源文件构建出页面

**Comment by NewX9** [comment]
搞不明白了，我先用docker run命令跑起来您的镜像文件，然后用docker exec进去修改src/config/api.ts ：该文件中配置 baseUrl 变量为我服务器的地址:端口，然后再用docker commit命令创建一个新的镜像，再用docker run命令运行修改完配置文件的镜像文件，请求的还是[http://localhost:5000/login这个地址。浏览器也清理过缓存什么的。

**Comment by cxOrz** [comment]
你有没有运行 pnpm build，让代码生效

**Comment by NewX9** [comment]
> 你有没有运行 pnpm build，让代码生效

感谢，我没用pnpm build，用了之后生效了，在本地搭建的项目可以登录了，但在云服务器上的Status Code 显示 500 Internal  Server Error，云服务器还是没法登录，但本地可以了。

**Comment by NewX9** [comment]
[https://github.com/cxOrz/chaoxing-sign-cli/issues/126](url) ，看到了这个，我也是同样的问题。

**Comment by cxOrz** [comment]
那就换个服务器吧

**Comment by NewX9** [comment]
> 那就换个服务器吧

换成华为云可行。
