### ISSUE TITLE
二维码enc貌似不再是固定值了

### ISSUE THREAD

**Issue by uuxysyj** [cxOrz/chaoxing-sign-cli#157]
二维码enc随着10秒切换变化了

**Comment by cxOrz** [comment]
有几个办法仅供参考：

1. 部署Web项目，配置腾讯云OCR，找挚友在他手机上登录账号，手动签到时，点击选择图片，选择拍照，在新二维码出现后立刻拍照，就能在2s内识别出来（照片像素越高越慢），点击签到即可。
2. 配置 cq-http 服务器，配置 QQ 机器人，发现二维码签到将询问二维码，只需用QQ拍照并发送二维码，即可迅速识别并自动完成签到。

这两种办法很快，一般在10秒内都可以轻轻松松完成。

**Comment by shunshunstudy** [comment]
qq机器人不会搭建，自己有阿里云服务器

**Comment by shunshunstudy** [comment]
可以发一下在服务器上搭建qq机器人的帮助文档吗

**Comment by cxOrz** [comment]
> 可以发一下在服务器上搭建qq机器人的帮助文档吗

https://docs.go-cqhttp.org/guide/quick_start.html

**Comment by shunshunstudy** [comment]
![image](https://user-images.githubusercontent.com/70955326/230764750-1a31e22c-0bfa-4c89-88c7-ba03b2b1a82c.png)

**Comment by shunshunstudy** [comment]
怎么解决？

**Comment by shunshunstudy** [comment]
![image](https://user-images.githubusercontent.com/70955326/230764976-5bcc1399-49d8-40e4-8563-07fe47a4b580.png)

**Comment by cxOrz** [comment]
去 cq-http 的仓库问😂

**Comment by Kenneth-zh** [comment]
那现在想逃课确实就没啥好办法了

**Comment by Kenneth-zh** [comment]
不知道用telegram bot可不可行

**Comment by XayahY** [comment]
我说怎么读取了enc还是无法签到 有点难办了

**Comment by SummonHIM** [comment]
成功经验，包括山卡拉学校网络很卡的情况；
环境：后端电信家宽公网ip，软路由pve虚拟机ubuntu lxc container，letsencrypt的ssl（nginx反代），填了腾讯ocr key。前端cloudflare pages，套了zerotrust邮箱认证，改了二维码为腾讯ocr。
手机：Rm Note 7（MIUI12/MiCam4.2），Rm K40 Pro（MIUI14/MiCam4.5）
浏览器拍摄二维码时候，将图片比例改为（1：1）避免腾讯云非横屏OCR识别失败，设置里照片质量低。浏览器调用MiCam的设定不影响桌面进入MiCam的设定。
