### ISSUE TITLE
查询签到时无法查找到群聊里面的签到

### ISSUE THREAD

**Issue by RoromoriYuzu** [cxOrz/chaoxing-sign-cli#16]
课程里面的签到是可以正常获取到，但如果在群聊里面有签到的话，获取不到。

**Comment by miaochenxi** [comment]
不太清楚。。没遇到过这种情况

**Comment by newtool** [comment]
![image](https://user-images.githubusercontent.com/32417809/161428446-e2bf2417-2302-4789-9e87-0cb7c67dc0e2.png)
![73C9C71CD59A63428C95D81C78A7C583](https://user-images.githubusercontent.com/32417809/161428504-b5abdfb5-1bb6-46e3-ae97-451370a41304.jpg)
比如图片里的，在群聊里发布签到的话
![image](https://user-images.githubusercontent.com/32417809/161428530-5989b833-aae3-43f3-a87c-6e8389b34612.png)

**Comment by miaochenxi** [comment]
目前只能获取课程中的活动，或许日后会找到获取群聊中活动的方法🥹

**Comment by q2929843202** [comment]
> 目前只能获取课程中的活动，或许日后会找到获取群聊中活动的方法🥹

建议去看看https://github.com/cyanray/cx-auto-sign这个仓库有没有思路  他就是检测群聊 用作者你这边的我自己开的课程测试自动签到检测不到 用他的就可以

**Comment by cxOrz** [comment]
他的代码有些老，看了看实现差不多，但是我这边确实收不到群聊消息；

这十小时的发现：
- 新注册的未认证帐号会有一些限制，比如收不到消息；
- 无课程的群聊签到接口，和有课程的不一样；

现在已经支持无课程群聊签到，已经测试过，更新代码 `git pull`。
运行 `npm run monitor`  启动监听，发布群聊签到将自动签上。
