### ISSUE TITLE
docker第二条指令运行出现问题

### ISSUE THREAD

**Issue by Mironken** [cxOrz/chaoxing-sign-cli#160]
docker run -d -p 80:80 -p 5000:5000 chaoxing-sign-cli
运行完提示无法拉去项目，需要登入或者没此项目，使用docker login 后还是无法拉去，则使用docker run -d -p 80:80 -p 5000:5000  cxorz/chaoxingsigncli
但运行成功后无法登入

**Comment by wdssfff00** [comment]
第一条命令
docker run -d -p 80:80 -p 5000:5000 chaoxing-sign-cli
应该是
docker run -d -p 80:80 -p 5000:5000 cxorz/chaoxingsigncli
(因为docker网上公共库里作者就是写的chaoxingsigncli，而拉取格式应该是   用户名/项目名   )

第二条的无法登入问题我现在也是，emmmm，我去提一下，看了置顶lssues没解决

**Comment by Mironken** [comment]
> 第一条命令 docker run -d -p 80:80 -p 5000:5000 chaoxing-sign-cli 应该是 docker run -d -p 80:80 -p 5000:5000 cxorz/chaoxingsigncli (因为docker网上公共库里作者就是写的chaoxingsigncli，而拉取格式应该是 用户名/项目名 )
> 
> 第二条的无法登入问题我现在也是，emmmm，我去提一下，看了置顶lssues没解决

对的，我去docker仓库看了一下，名字前面应该有个cxorz，但现在登入问题确实无法解决

**Comment by gufei233** [comment]
> > 第一条命令 docker run -d -p 80:80 -p 5000:5000 chaoxing-sign-cli 应该是 docker run -d -p 80:80 -p 5000:5000 cxorz/chaoxingsigncli (因为docker网上公共库里作者就是写的chaoxingsigncli，而拉取格式应该是 用户名/项目名 )
> > 第二条的无法登入问题我现在也是，emmmm，我去提一下，看了置顶lssues没解决
> 
> 对的，我去docker仓库看了一下，名字前面应该有个cxorz，但现在登入问题确实无法解决

可以使用git clone https://github.com/cxOrz/chaoxing-sign-cli.git 拉取后进入文件修改好IP 然后再docker build

**Comment by Mironken** [comment]
搞定了等一下写一下docker的完整指令，感谢前面大佬们的分享

**Comment by Mironken** [comment]
1.拉取容器 docker pull cxorz/chaoxingsigncli:latest
2.运行容器 docker run -d -p 80:80 -p 5000:5000 cxorz/chaoxingsigncli:latest
3.查看容器ID docker ps
4.进入容器 docker exec -it 容器ID /bin/bash（或/bin/sh）
5.进入容器的配置文件目录 cd /app/apps/web/src/config
6.修改配置文件 vi api.ts （修改const baseUrl ='http://ip地址: 5000'）
7.返回web文件夹 cd /app/apps/web
8.重新构建 pnpm build
9.重新运行 pnpm serve
10.退出容器 exit
11.重启容器 docker restart 容器ID或容器名
12.打开网站测试
