### ISSUE TITLE
Docker部署后登陆无反应(实在是看了置顶没解决问题，没办法所以来请教了)

### ISSUE THREAD

**Issue by wdssfff00** [cxOrz/chaoxing-sign-cli#161]
<img width="261" alt="uTools_1681051865399" src="https://user-images.githubusercontent.com/83413772/230779831-34261e83-d1b6-4dbd-afc5-08f90a886d32.png">
看了置顶[Docker部署后无法访问API端口](https://github.com/cxOrz/chaoxing-sign-cli/issues/133)问题后总结如下
1、去容器目录/app/apps/web/src/config/api.ts  修改baseUrl
尝试修改为   http://172.17.0.8:5000，，http://192.168.1.5:5000，，http://192.168.1.5:12345(自己设置映射的端口)，，http://0.0.0.0:12345
2、docker exec -it chaoxing-sign-cli bash 进入容器，cd到web文件夹，执行
pnpm build   成功
pnpm serve   (报错提示Command failed with ENOENT: servespawn serve ENOENT)  不过没事

3、外部portainer面板重启chaoxing-sign-cli这个容器

重启后啥也没变，还是
Nginx: http://localhost:80
API Server: http://localhost:5000

寄😭

想法：
目前还不清楚为啥修改无效，修复方法还提不出来，真的抱歉😭，目前个人想法是将baseUrl写入配置或者env，重启容器检测配置修改后自动根据配置重新构建web和后端
结语：
docker确实好用，代码一键搭建完成，而且更容易保活，不用担心因为系统环境混乱（比如刚需项目的node依赖版本和本项目冲突）或者各佛系掉线错过签到

**Comment by cxOrz** [comment]
这两行是写死的，让你知道默认情况下从哪里访问，不用在意这两行Log输出。
```
Nginx: http://localhost:80
API Server: http://localhost:5000
```

你试试能不能正常登陆、签到就行了，点击没反应的话，看看是不是服务器IP在超星封控范围内，或者是接口地址没请求对（F12打开看看）。

**Comment by wdssfff00** [comment]
结案，在作者点明这两行Log输出是写死的之后我就有自信找别的原因，上面那些步骤完成后F12查询请求地址发现就是我设定地址，这时我就怀疑是不是上面设定的地址没联通
![1111](https://user-images.githubusercontent.com/83413772/230781415-c6427943-26ad-496f-82e5-cfda0e499598.png)

排查：
1、直接浏览器请求，发现无法连通，网页没反应，这里放一张成功截图
<img width="732" alt="uTools_1681053786749" src="https://user-images.githubusercontent.com/83413772/230781572-32456e5a-ecdc-488e-a9f1-a582a3fff434.png">
2、排查整个请求通路，
我自己挂项目的服务器防火墙对这个端口是否限制-------宝塔安全里设置是否放开端口------上游路由器端口转发(或者云服务器防火墙)-----你所连网络路由器防火墙------本机的端口防火墙

我是端口转发忘记改回docker设置的，导致设置端口没法通过路由器防火墙
<img width="723" alt="uTools_1681053493155" src="https://user-images.githubusercontent.com/83413772/230781268-dd23483c-8d59-4de3-9fdf-c1f5e49e0cff.png">

这里本机原来是
IP 192.168.1.57, 端口 5000 位于 lan
而我docker映射出来端口55441，在这里应该改成55441
