### ISSUE TITLE
隐私问题---真的很抱歉半夜叨扰

### ISSUE THREAD

**Issue by wdssfff00** [cxOrz/chaoxing-sign-cli#162]
尴尬，刚才舍友说我这样不是直接把自己名字露外面去了emmmm
能否加入web注册功能，自己登陆只看到自己的账号这样
（其实我觉得名字也加密直接在登陆超星的时候加入一个必须设置昵称的功能，只靠昵称认更好🤣）

**Comment by cxOrz** [comment]
有没有一种可能，现在就是自己登录只能看到自己的账号。一切都存在你的浏览器里，别人也访问不到哇

**Comment by wdssfff00** [comment]
![A_7$P9)S4 J17H4OB@S)M1J](https://user-images.githubusercontent.com/83413772/230782389-6e6ed60a-c73c-48f3-a0b1-50d84cc18ef0.png)
