### ISSUE TITLE
位置签到问题

### ISSUE THREAD

**Issue by Hallaey** [cxOrz/chaoxing-sign-cli#165]
你好，我习惯用pnpm dev后直接用网页配置，但是我网页监听的位置是我第二次改好的（即108，34），每次开了网页监听也都能用。今天想找到源文件正好要改cq-http的东西，看到了保存在chaoxing-sign-cli\apps\server\src\index.ts的文件还是我第一次的位置（即113，34）。请问怎么办？
![3G R N69GH_9 }P2PI%M45D](https://user-images.githubusercontent.com/62861493/231372083-234b4541-160b-4e6d-8dec-1e5ae45353cb.png)

**Comment by Hallaey** [comment]
对了，同目录下的monitor.ts的位置也是错误位置（即113，34），我不知道网页这个数据保存在哪里了。顺便也想问一下改这个的配置文件在哪里。谢谢

**Comment by Hallaey** [comment]
现在我把index和monitor的两个配置文件位置都改为(108,34)并重新启动服务，添加新用户时仍然是(113,34)

**Comment by cxOrz** [comment]
网页里的所有东西都存在浏览器本地，和服务端没关系。直接右键卡片，改你的配置就行了。

**Comment by cxOrz** [comment]
在网页下的 IndexedDB 里存着

**Comment by Hallaey** [comment]
> 网页里的所有东西都存在浏览器本地，和服务端没关系。直接右键卡片，改你的配置就行了。

那我如果用pnpm start启动的话，就可以调取这两个脚本的配置了吗

**Comment by cxOrz** [comment]
pnpm start 执行的是 index.js
pnpm monitor 执行的是 monitor.js

**Comment by Hallaey** [comment]
好的谢谢大佬！
