### ISSUE TITLE
二维码签到

### ISSUE THREAD

**Issue by Hallaey** [cxOrz/chaoxing-sign-cli#166]
大佬你好，我要搞cqhttp机器人接这个项目，现在已经绑定好了但是需要识别QR码，在腾讯云买的识别需要哈希值才能成功申请...请问在哪里找...
![)}Z~I3PXYZR` 5}0K D()XG](https://user-images.githubusercontent.com/62861493/231387432-4b4ad06b-3cdf-4668-b3e2-c6edb639313c.png)

**Comment by cxOrz** [comment]
不用申请SDK啊。
https://console.cloud.tencent.com/cam/capi

**Comment by Hallaey** [comment]
> 不用申请SDK啊。 https://console.cloud.tencent.com/cam/capi

我是小丑，抱歉了

**Comment by Hallaey** [comment]
大佬好，我又来了，我将secretid和key都导入进apps\server\src中了，但是二维码签到的时候，我给qq发二维码图片，他只认识图片不能直接识别

**Comment by cxOrz** [comment]
通过 pnpm serve 运行的话：
有两个 env.json 你填入的是哪个？如果是 src 里的，需要运行 pnpm build 生效；如果是 bulid 下的，就不用了。
通过 pnpm dev 的话，用的就是 src 下的配置。

**Comment by cxOrz** [comment]
检测到二维码签到，他会告诉你让你发图，你发给他就行了

**Comment by cxOrz** [comment]
还不行就看看到底有没有开通了 **通用文字识别** 或者 **智能扫码**

**Comment by Hallaey** [comment]
env的serverless要改为true吗？

**Comment by Hallaey** [comment]
是这样
![`MZ@`R{PPKH%NA)OTBS }JC](https://user-images.githubusercontent.com/62861493/231399293-a7304e80-473c-4776-98ff-839c70abb6ac.png)

**Comment by Hallaey** [comment]
算了，我把全部文件删掉从头开始来一遍吧

**Comment by Hallaey** [comment]
没办法。没成功。下面是我的全部步骤：
1.下载chaoxingsigncli压缩包解压放在桌面重新命名为chaoxing-sign-cli。用cmd进入pnpm install，之后直接pnpm dev，发现可以启动，遂关闭（cmd和网页都关闭）。
2.下载go-cqhttp压缩包并解压至桌面重命名为go-cqhttp。
![QQ截图20230412170308](https://user-images.githubusercontent.com/62861493/231408864-b91a3d19-2234-46d2-943e-e06896d3a077.png)
选择正向ws安装后用Android watch扫码登陆成功。不关闭。
3.先将SecretID和KEY都在apps/server/src中的env.json填入，随后保存关闭，用pnpm dev成功打开网页，在localhost:3000中配置同学的监听配置，将ws网址和qq都输入，成功链接cqhttp。
4.发起二维码签到，cqhttp有二维码签到的提醒，无奈我发图片过去他不能识别签到。随即结束。
![QQ截图20230412170105](https://user-images.githubusercontent.com/62861493/231409701-7faea320-c85c-4762-b07a-12f97ffe6c50.png)

**Comment by Hallaey** [comment]
腾讯云的扫描识别统计是0

**Comment by cxOrz** [comment]
![image](https://user-images.githubusercontent.com/32982052/231415586-d2755e4a-b232-46ec-9edd-2284ce111bc0.png)

我试了试很正常，你看看是不是腾讯云那没弄对，[API Explorer](https://cloud.tencent.com/login?s_url=https%3A%2F%2Fconsole.cloud.tencent.com%2Fapi%2Fexplorer%3FProduct%3Docr%26Version%3D2018-11-19%26Action%3DQrcodeOCR) 试试看能不能正常识别图像

**Comment by cxOrz** [comment]
而且，智能扫码不需要买，每个月免费1000次

**Comment by Hallaey** [comment]
> ![image](https://user-images.githubusercontent.com/32982052/231414835-14812012-05f0-48bb-81a2-0f920559d5e1.png)
> 这里没有回复吗
奇怪哎，我的机器人不会说话。

**Comment by Hallaey** [comment]
> ![image](https://user-images.githubusercontent.com/32982052/231415586-d2755e4a-b232-46ec-9edd-2284ce111bc0.png)
> 
> 我试了试很正常，你看看是不是腾讯云那没弄对，[API Explorer](https://cloud.tencent.com/login?s_url=https%3A%2F%2Fconsole.cloud.tencent.com%2Fapi%2Fexplorer%3FProduct%3Docr%26Version%3D2018-11-19%26Action%3DQrcodeOCR) 试试看能不能正常识别图像

好的，我等会试试

**Comment by Hallaey** [comment]
> 而且，智能扫码不需要买，每个月免费1000次

好的，我是冤种

**Comment by Hallaey** [comment]
> ![image](https://user-images.githubusercontent.com/32982052/231414835-14812012-05f0-48bb-81a2-0f920559d5e1.png)
> 这里没有回复吗

奇怪哎，我的机器人不会说话

**Comment by cxOrz** [comment]
你Node几？

**Comment by Hallaey** [comment]
> 你Node几？

18.15.0LTS

**Comment by cxOrz** [comment]
要不你直接用 pnpm monitor 运行，试试看

**Comment by cxOrz** [comment]
看看签到报不报什么错

**Comment by Hallaey** [comment]
除了二维码签到，别的都正常的。还没试验拍照签到。我先休息一会🤡发自我的 iPhone在 2023年4月12日，17:35，Hanasaki ***@***.***> 写道：﻿
看看签到报不报什么错

**Comment by cxOrz** [comment]
拍照签到暂时不支持从QQ发，需要传到网盘，具体看说明

**Comment by Hallaey** [comment]
> 拍照签到暂时不支持从QQ发，需要传到网盘，具体看说明

收到 会看 感谢

**Comment by Hallaey** [comment]
你好，是我的问题，是我不会配置腾讯云OCR...我百度了并且下载了腾讯云的Python SDK...我不知道怎么配置OCR。
另，monitor除了二维码，一切运行正常。感谢。
