### ISSUE TITLE
 求助postman 二维码接口返回非法请求怎么解决

### ISSUE THREAD

**Issue by 624067008** [cxOrz/chaoxing-sign-cli#167]
![image](https://user-images.githubusercontent.com/94523036/231454181-8220ab15-aff4-460e-b232-27cabccf1cab.png)

**Comment by cxOrz** [comment]
需要先进行预检请求

**Comment by 624067008** [comment]
没懂  我看到这里只有1个请求  预检请求是哪个

**Comment by 624067008** [comment]
是预签到吗
![image](https://user-images.githubusercontent.com/94523036/231460101-930ff88f-77bd-4eaa-b9d4-61047137cd22.png)

**Comment by cxOrz** [comment]
是的
![image](https://user-images.githubusercontent.com/32982052/231460338-77b43d62-2e77-4eea-b5ef-066e11b3bba4.png)
