### ISSUE TITLE
监听关闭了还是自动签了？

### ISSUE THREAD

**Issue by SJpoor** [cxOrz/chaoxing-sign-cli#168]
请问如何完全关闭一个账号的监听？我把server/build/configs/storage.json里的用户删除了也没有用，ui页面还有，后来发现这里保存的是手动签到保存的账号信息。ui显示账号监听已经关闭了，但还是自动签到。

**Comment by cxOrz** [comment]
Windows还是Linux

**Comment by SJpoor** [comment]
linux

**Comment by SJpoor** [comment]
> Windows还是Linux
linux

**Comment by cxOrz** [comment]
回头我留意以下这个问题，如果遇到这个问题了，尝试重启一下，或者换个 Distro。
这个我至今还没遇到过

**Comment by cxOrz** [comment]
c213e87d7d7f1b1cc351f60d96b02121f6878014

**Comment by SJpoor** [comment]
> 

成功解决了，十分感谢
