### ISSUE TITLE
为什么不能添加用户

### ISSUE THREAD

**Issue by admi-n** [cxOrz/chaoxing-sign-cli#169]
用docker的方式部署
在添加用户出现
![image](https://user-images.githubusercontent.com/34176629/231698333-e09ac7ae-984e-4855-bbf4-59f492d096bf.png)
![image](https://user-images.githubusercontent.com/34176629/231698420-03ad1797-798b-485b-bb96-b5720502f238.png)
![image](https://user-images.githubusercontent.com/34176629/231698957-d967e75e-2819-49da-ba3b-bbaaf1e980b9.png)
![image](https://user-images.githubusercontent.com/34176629/231699163-a49778a6-cbc9-4d3a-bf71-ddf38ab55b00.png)

**Comment by cxOrz** [comment]
累了，相同的问题，提了n遍… 可否先查查，思考思考，真解决不了再来问问，我谢谢🥹
