### ISSUE TITLE
二维码enc变化问题

### ISSUE THREAD

**Issue by cxOrz** [cxOrz/chaoxing-sign-cli#178]
两个办法供参考：
1. 配置QQ机器人、腾讯OCR，并启动监听模式。当检测到二维码签到时，将提醒用户发送二维码图片，在签到结束前任意时间发送二维码，即可自动识别完成签到（建议打开QQ相机，二维码刷新后立刻按下快门发送，通常3秒内即可完成签到，图片质量越低识别越快）
2. Web页面手动查询签到，显示出二维码签到后，点击选择图片，选择使用相机，等二维码刷新后立刻按下快门，识别完成点击签到即可。

**Comment by Lakr233** [comment]
寄了 现在 enc 会变了 玩坏了 🥺

**Comment by cxOrz** [comment]
不仅如此 要毕业了 以后应该也不会投入多少精力维护了🥹

**Comment by Lakr233** [comment]
问题不大 我明年毕业 要上的课应该只剩下两个月了！

**Comment by cxOrz** [comment]
好耶ヽ(✿ﾟ▽ﾟ)ノ

我以为你都工作好多年了🤣（看推特上发内容的不像学生  技术极强的工作大佬

**Comment by hwh12322** [comment]
鱼鱼了，到我就今年就不行了是吧

**Comment by Lakr233** [comment]
> 鱼鱼了，到我就今年就不行了是吧

抱抱你！

**Comment by AmiroKD** [comment]
> 寄了 现在 enc 会变了 玩坏了 🥺

现在enc也获取不到了

**Comment by Lakr233** [comment]
> > 寄了 现在 enc 会变了 玩坏了 🥺
> 
> 现在enc也获取不到了

~~反正毕业了 祖国的下一代多努力没什么不好~~

**Comment by samoYYY** [comment]
居然是四个小时前的回答

**Comment by KirisameMashiro** [comment]
很难不让人sad
