### ISSUE TITLE
疑似拍摄二维码模糊会导致监听自动退出，使该课程无法再次签到

### ISSUE THREAD

**Issue by Coppelia39** [cxOrz/chaoxing-sign-cli#179]
我用近处拍摄和远距离拍摄进行多次测试，发现远距离拍摄时会有以下报错
![捕获](https://github.com/cxOrz/chaoxing-sign-cli/assets/125564614/ec0ba9c0-92b8-4d7f-b886-aa9fcd134141)
之前测试的时候，二维码在图片上传过程中刷新，机器人会返回”签到失败，请重新扫描“，再次拍摄后即可签到成功，但实战时向群聊发送图片机器人无任何反应，返回控制台看到报错，因此产生如题的猜测，不知是否因此出错？另外：今天我在未对服务器项目进行任何变动的情况下在浏览器使用UI点击监听后卡住，但却能使用UI正常登陆账号以及访问后端接口，只有在shell里输入pnpm monitor才能正常启动监听，这个问题也是首次出现，劳烦您帮我定位一下问题出现的可能原因。附：
![image](https://github.com/cxOrz/chaoxing-sign-cli/assets/125564614/c01b74da-e38f-44fc-abc1-e036ffe83b35)

**Comment by cxOrz** [comment]
把远距离拍摄失败的那张照片发出来吧，我调试一下

**Comment by cxOrz** [comment]
另外想问一下，最近用 pnpm monitor 运行的监听模式，能正常使用吗

**Comment by Coppelia39** [comment]
@cxOrz 这个清晰度识别不到信息
![-61c19f27ea51aae6](https://github.com/cxOrz/chaoxing-sign-cli/assets/125564614/75922e4b-d3ff-4112-8187-86249e02031a)
这个清晰度可以识别到
![23d225009d9f9a2c](https://github.com/cxOrz/chaoxing-sign-cli/assets/125564614/093c0448-6c6d-4ef4-97cb-a2778fdec902)
昨天测试时pnpm monitor指令可以正常运行以及签到，只是ui点击监听后停在加载中

**Comment by cxOrz** [comment]
更新了，在试试看。以后应该即使匹配不到enc也不会异常退出

**Comment by Coppelia39** [comment]
问题已解决
