### ISSUE TITLE
二维码签到

### ISSUE THREAD

**Issue by 1594002347** [cxOrz/chaoxing-sign-cli#182]
作者您好，打扰了。由于二维码签到不能无视十秒签到了，您给出的解决方案很完美，可通过搭建QQ机器人进行签到。不过如果增加联动模式的话，去上课的同学通过扫码课程二维码进行签到后，其他人开启监听后可立马对该课程进行自动签到，这样感觉成功率会比较高一些。

**Comment by cxOrz** [comment]
你们可以都提前启动监听模式，拉个群，遇到签到机器人都会询问二维码，签到的同学把二维码发到群里，一下就全签了

**Comment by 1594002347** [comment]
好嘞，感谢
