### ISSUE TITLE
docker部署的问题

### ISSUE THREAD

**Issue by ZefanHu** [cxOrz/chaoxing-sign-cli#183]
![image](https://github.com/cxOrz/chaoxing-sign-cli/assets/81904038/7ba129f2-649d-405c-a548-f5b94a64bec9)
这个算部署成功了吗？我尝试登录但是等了大约2分钟，网页看不到响应。应该是没有登录成功
![image](https://github.com/cxOrz/chaoxing-sign-cli/assets/81904038/13fbdbdb-2a0a-4969-8910-5c361ee166d2)

**Comment by ZefanHu** [comment]
你好，我按照教程pull然后docker run -d -p 999:80 -p 5000:5000 ghcr.io/cxorz/chaoxing-sign-cli:latest
试了两次都是有两个容器，有一个停止的，我启动不了。服务器是海外。

**Comment by ZefanHu** [comment]
不好意思，刚刚重启的了一下发现是端口的问题，改成docker run -d -p 8888:80 -p 5555:5000 ghcr.io/cxorz/chaoxing-sign-cli:latest就运行了，剩下的问题是登录没有响应，帮忙看看，非常感谢。
![image](https://github.com/cxOrz/chaoxing-sign-cli/assets/81904038/5dcdd856-22bd-493d-b163-9290a9b7f37f)

**Comment by cxOrz** [comment]
你看看访问的接口对不对。
接口要是通了的话，可以通过接口的URL访问到欢迎页；
