### ISSUE TITLE
纯电脑小白，pnpm下载过程中报了个错，并且pnpm build也报错

### ISSUE THREAD

**Issue by mtx926** [cxOrz/chaoxing-sign-cli#188]
![Screenshot_20230719_132037 1](https://github.com/cxOrz/chaoxing-sign-cli/assets/139613466/2ea16269-46c2-4085-b0ca-1a71ad02ee0e)
![Screenshot_20230719_131400 1](https://github.com/cxOrz/chaoxing-sign-cli/assets/139613466/870df42e-9f5c-4a10-914e-21697852c5ab)
没有相应的基础，还请大佬帮忙看下，谢谢

**Comment by cxOrz** [comment]
pnpm install  不是 node_module install。照着README来应该不会有问题

**Comment by cxOrz** [comment]
仔细看README

**Comment by mtx926** [comment]
> pnpm install 不是 node_module install。照着README来应该不会有问题

第一张图里面报的一堆WARN就是我在pnpm install，并且之后pnpm build的时候也报错了
![Screenshot_20230721_130330 1](https://github.com/cxOrz/chaoxing-sign-cli/assets/139613466/772b16f3-1630-4445-b02f-82405ea631b8)

**Comment by cxOrz** [comment]
要不跟着README在重新走一遍，先把本地的东西都删了

**Comment by WoAiNianChu** [comment]
> ![截图_20230719_132037 1](https://user-images.githubusercontent.com/139613466/254471127-2ea16269-46c2-4085-b0ca-1a71ad02ee0e.jpg) ![Screenshot_20230719_131400 1](https://user-images.githubusercontent.com/139613466/254471343-870df42e-9f5c-4a10-914e-21697852c5ab.jpg) 没有相应的基础，还请大佬帮忙看下，谢谢

解决了嘛，我也遇到了同样的问题，之前安装记得没有这个问题

**Comment by WoAiNianChu** [comment]
> > pnpm install 不是 node_module install。照着README来应该不会有问题
> 
> 第一张图里面报的一堆WARN就是我在pnpm install，并且之后pnpm build的时候也报错了 ![截图_20230721_130330 1](https://user-images.githubusercontent.com/139613466/255077805-772b16f3-1630-4445-b02f-82405ea631b8.jpg)

我刚刚已经解决了这个问题。如果按照作者文档走，会安装node，但是node好像不会附带npm，所以出现了该问题。
卸载node
apt remove nodejs
删掉与之关联的全局模块
rm -rf /data/data/com.termux/files/usr/lib/node_modules
安装nodelist
pkg install nodejs-lts
其他的和作者文档走就行，除了这一步node安装
