### ISSUE TITLE
容器登录失败解决

### ISSUE THREAD

**Issue by biluokong** [cxOrz/chaoxing-sign-cli#192]
原因：web端访问server端默认ip为localhost，不会改变，这会导致访问server端的请求失败。
解决方法：修改chaoxing-sign-cli-4.5.5\apps\web\src\config下的api.js中的第一行为：
const baseUrl = 'http://' + window.location.hostname + ':5000';
然后使用项目下自带的Dockerfile文件重新构建容器即可，这样可以让局域网内的访问和使用云服务器ip访问都没有问题。

如果不想自己构建容器，可以使用我重新构建好的容器：
docker pull biluoer/chaoxing:1.0
docker run -d -p 3000:80 -p 5000:5000 --name chaoxing biluoer/chaoxing:1.0

**Comment by cxOrz** [comment]
其实你可以直接把这行代码发个PR 💭
