### ISSUE TITLE
怎么配置，才能让外面的访问到

### ISSUE THREAD

**Issue by Xiao-yux** [cxOrz/chaoxing-sign-cli#195]
![image](https://github.com/cxOrz/chaoxing-sign-cli/assets/79674967/c203f0e1-75df-49ac-9104-af63ea606c8d)
我更改src/config/api.ts后也没有用，应该怎么配置才能让局域网的电脑访问到

**Comment by XHQ6666** [comment]
可以使用 Nginx 代理网页

**Comment by cxOrz** [comment]
你们服务器端口开放了吗

**Comment by Xiao-yux** [comment]
![image](https://github.com/cxOrz/chaoxing-sign-cli/assets/79674967/25ca1dfe-4bef-4571-b861-33e88dd4d71f)
可以看到了，但是页面是空的，帮我看看是什么问题

**Comment by XHQ6666** [comment]
> ![image](https://github.com/cxOrz/chaoxing-sign-cli/assets/79674967/25ca1dfe-4bef-4571-b861-33e88dd4d71f)
> 可以看到了，但是页面是空的，帮我看看是什么问题

代理网页不需要加上 `root` 和 `index` 网页文件，只需要 `proxy_pass` 即可
