### ISSUE TITLE
关于接口问题

### ISSUE THREAD

**Issue by 917564927** [cxOrz/chaoxing-sign-cli#207]
就是已经看到欢迎超星学习通那个界面了，但是具体怎么利用这个接口api，访问其他目录都显示notfound

**Comment by cxOrz** [comment]
可以从代码里，看一下请求参数有哪些，请求方式是GET还是POST。按照同样的方式调用

**Comment by 917564927** [comment]
你看方不方便整个例子，就好比登录学习通的那个示例

**Comment by cxOrz** [comment]
https://github.com/cxOrz/chaoxing-sign-cli/tree/v4.1.0/apps/server

**Comment by cxOrz** [comment]
可以看一下这个，4.1.0的这个readme里有接口详情，你看了就知道怎么调了
