### ISSUE TITLE
报错问题，纯小白

### ISSUE THREAD

**Issue by syhhyl** [cxOrz/chaoxing-sign-cli#208]
pnpm start 后
输入密码后，报出如图错误
<img width="654" alt="image" src="https://github.com/cxOrz/chaoxing-sign-cli/assets/61073069/c5a1dca3-f804-4890-aa9a-3b09b319fd8b">

**Comment by skyclouds2001** [comment]
返回了个网页

**Comment by Ceiso1** [comment]
这个是ip被ban了 你可以ping一下学习通的网页
