### ISSUE TITLE
turbo 错误

### ISSUE THREAD

**Issue by taya3303** [cxOrz/chaoxing-sign-cli#211]
/chaoxing-sign-cli (main)
$ pnpm build
 WARN  This project is configured to use v7.28.0 of pnpm. Your current pnpm is v9.0.6

> chaoxing-sign@4.3.5 build C:\Users\30977\chaoxing-sign-cli
> turbo run build

'turbo' is not recognized as an internal or external command,
operable program or batch file.
 ELIFECYCLE  Command failed with exit code 1.

**Comment by cxOrz** [comment]
有没有安装依赖
