### ISSUE TITLE
CORS服务器端口跨域问题

### ISSUE THREAD

**Issue by lonlf** [cxOrz/chaoxing-sign-cli#213]
在登陆的时候fetch请求因为两个端口不同出现了跨域问题，这个该怎么解决呀？（用的docker部署）

**Comment by lonlf** [comment]
发现用API工具访问IP:5000/login直接报500了；但是IP:5000是正常的;
这是日志：
```
  SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
      at JSON.parse (<anonymous>)
      at userLogin (/app/apps/server/build/functions/user.js:39:14)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/apps/server/build/serve.js:30:20
      at async /app/apps/server/build/serve.js:283:5
      at async bodyParser (/app/node_modules/.pnpm/koa-bodyparser@4.3.0/node_modules/koa-bodyparser/index.js:95:5)
```
它为什么会报`Unexpected token`呢？是直接doker构建的容器，有大佬知道是为什么吗

**Comment by lonlf** [comment]
这是控制台：
```
数据库打开成功
服务器外网IP/:1  Access to fetch at 'http://服务器外网IP:5000/login' from origin 'http://服务器外网IP:10105' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
index.ad44e3aa.js:152 
        
        
        POST http://服务器外网IP:5000/login net::ERR_FAILED 500 (Internal Server Error)
(匿名) @ index.ad44e3aa.js:152
Vt @ index.ad44e3aa.js:152
v @ index.ad44e3aa.js:153
i @ index.ad44e3aa.js:153
Og @ index.ad44e3aa.js:29
Fg @ index.ad44e3aa.js:29
zg @ index.ad44e3aa.js:29
wf @ index.ad44e3aa.js:29
Ih @ index.ad44e3aa.js:29
(匿名) @ index.ad44e3aa.js:29
od @ index.ad44e3aa.js:32
nh @ index.ad44e3aa.js:29
Na @ index.ad44e3aa.js:29
Ic @ index.ad44e3aa.js:29
e1 @ index.ad44e3aa.js:29
index.ad44e3aa.js:152 
        
        
       
        
        Uncaught (in promise) TypeError: Failed to fetch
    at index.ad44e3aa.js:152:7069
    at new Promise (<anonymous>)
    at Vt (index.ad44e3aa.js:152:7042)
    at Object.v [as onOK] (index.ad44e3aa.js:153:136105)
    at i (index.ad44e3aa.js:153:130077)
    at Object.Og (index.ad44e3aa.js:29:9862)
    at Fg (index.ad44e3aa.js:29:10016)
    at zg (index.ad44e3aa.js:29:10073)
    at wf (index.ad44e3aa.js:29:31506)
    at Ih (index.ad44e3aa.js:29:31923)
```

**Comment by cxOrz** [comment]
> 发现用API工具访问IP:5000/login直接报500了；但是IP:5000是正常的; 这是日志：
> 
> ```
>   SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
>       at JSON.parse (<anonymous>)
>       at userLogin (/app/apps/server/build/functions/user.js:39:14)
>       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>       at async /app/apps/server/build/serve.js:30:20
>       at async /app/apps/server/build/serve.js:283:5
>       at async bodyParser (/app/node_modules/.pnpm/koa-bodyparser@4.3.0/node_modules/koa-bodyparser/index.js:95:5)
> ```
> 
> 它为什么会报`Unexpected token`呢？是直接doker构建的容器，有大佬知道是为什么吗

ip被ban。

**Comment by lonlf** [comment]
> > 发现用API工具访问IP:5000/login直接报500了；但是IP:5000是正常的; 这是日志：
> > 
> > ```
> >   SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
> >       at JSON.parse (<anonymous>)
> >       at userLogin (/app/apps/server/build/functions/user.js:39:14)
> >       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> >       at async /app/apps/server/build/serve.js:30:20
> >       at async /app/apps/server/build/serve.js:283:5
> >       at async bodyParser (/app/node_modules/.pnpm/koa-bodyparser@4.3.0/node_modules/koa-bodyparser/index.js:95:5)
> > ```
> > 
> > 它为什么会报`Unexpected token`呢？是直接doker构建的容器，有大佬知道是为什么吗
> 
> ip被ban。

被ban是因为服务商吗，放在本地

**Comment by lonlf** [comment]
> > 发现用API工具访问IP:5000/login直接报500了；但是IP:5000是正常的; 这是日志：
> > 
> > ```
> >   SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
> >       at JSON.parse (<anonymous>)
> >       at userLogin (/app/apps/server/build/functions/user.js:39:14)
> >       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> >       at async /app/apps/server/build/serve.js:30:20
> >       at async /app/apps/server/build/serve.js:283:5
> >       at async bodyParser (/app/node_modules/.pnpm/koa-bodyparser@4.3.0/node_modules/koa-bodyparser/index.js:95:5)
> > ```
> > 
> > 它为什么会报`Unexpected token`呢？是直接doker构建的容器，有大佬知道是为什么吗
> 
> ip被ban。

这个是服务商的问题吗，这样的话是只能部署在本地吗

**Comment by cxOrz** [comment]
可以部署在香港
