### ISSUE TITLE
网页端问题

### ISSUE THREAD

**Issue by gfh980** [cxOrz/chaoxing-sign-cli#214]
我部署了网页端并成功运行，手动可以打到指定位置，但监听不可以总是打到默认地址安徽坦克学院那，我也改了监听配置，但不管用

**Comment by cxOrz** [comment]
可以尝试用postman或者其他请求工具，按照监听调用的位置签到函数，发送请求，看签哪了。

**Comment by gfh980** [comment]
> 可以尝试用postman或者其他请求工具，按照监听调用的位置签到函数，发送请求，看签哪了。
好的感谢解答

**Comment by cxOrz** [comment]
班级签到，不一定管用，很久以前的代码了。课程签到可能还能用。
