### ISSUE TITLE
签到经常检测不到

### ISSUE THREAD

**Issue by bnrh** [cxOrz/chaoxing-sign-cli#29]

**Comment by bnrh** [comment]
![2b9c31227bd94ee61b88f58964e1786](https://user-images.githubusercontent.com/58646811/165874525-b09615c2-8e44-451c-8183-16d36d6e4909.jpg)
![image](https://user-images.githubusercontent.com/58646811/165874628-67d1ae45-c8d5-4c1e-8fe7-c99af9e1e40f.png)
这两个是运行截图

**Comment by miaochenxi** [comment]
- 检测时长是2小时
- 活动结束就检测不到了
- 课程发布的签到可以被检测
- 无课程的群聊发布的签到不能被检测

**Comment by cxOrz** [comment]
https://github.com/cxOrz/chaoxing-sign-cli/issues/33#issue-1229946219
