### ISSUE TITLE
关于开发计划

### ISSUE THREAD

**Issue by moxiaowk** [cxOrz/chaoxing-sign-cli#30]
大佬有考虑后期做成自动（定时）签到吗

**Comment by cxOrz** [comment]
没有，我感觉意义不大。所以交给有需要的人，自己fork一份然后添加这个功能。

**Comment by moxiaowk** [comment]
大佬可以看看这个项目 https://github.com/w964522982/xxtSign

**Comment by cxOrz** [comment]
还是不太想冒这个风险，循环检测签到对服务器进行大量请求，我怕有风险，比如把你的账号标记为疑似使用签到工具、账号异常、疑似机器人、疑似DDoS攻击、拉黑IP地址

**Comment by moxiaowk** [comment]
哦哦，也是😂
