### ISSUE TITLE
学习通密码带有特殊符号的时候会登入失败

### ISSUE THREAD

**Issue by HalcyonAzure** [cxOrz/chaoxing-sign-cli#31]
目前没有尝试复现，在我的密码为`*******~`的时候登入无法成功，更改为`*******`后则能够成功登入，感觉可能与特殊符号有关。

**Comment by cxOrz** [comment]
![图片](https://user-images.githubusercontent.com/32982052/166625945-f0b79c06-7618-461e-92bd-e79706f87bd5.png)

试了下，密码只能是字母和数字组合，按照超星的规则设置密码吧。

**Comment by HalcyonAzure** [comment]
> ![图片](https://user-images.githubusercontent.com/32982052/166625945-f0b79c06-7618-461e-92bd-e79706f87bd5.png)
> 
> 试了下，密码只能是字母和数字组合，按照超星的规则设置密码吧。

刚刚反应过来...可能是我当时注册的时间比较早，现在加以限制了，那就应该没有什么问题了，感谢。
