### ISSUE TITLE
关于上次被关闭的提问补充一下说明

### ISSUE THREAD

**Issue by bnrh** [cxOrz/chaoxing-sign-cli#33]
上次的问题我上传了截图，现在没有了，之前的问题后台可以看到的话可以再看看，针对作者大大的回复我补充说明一下：
1、当时的截图可以看到距离发布的签到相隔只有几分钟十几分钟
2、签到当时并未结束，手机学习通还可以进入签到页面
3、该签到是课程发布的，详见截图
![8638a4fb851983bc24bde40db098541](https://user-images.githubusercontent.com/58646811/167451146-ec47f8fe-fb71-49e1-a83b-f302c971a609.jpg)

**Comment by cxOrz** [comment]
- 二维码签到、手势签到、拍照签到，即使任务已结束，也可以正常打开，执行完签到后，才会提示 “签到已过期”。即使手机上还可以进入签到页面，任务也可能已结束。
- 再次检查过，有效活动期限的判定代码没有问题，距离发布7200秒以内且未结束的，会判定为有效活动。
- 如果对签到判定的时间有疑问，请复现一下问题，设置一个2h的签到，在距离发布1h50min时看下是否能检测到。
感谢反馈 ❤️
