### ISSUE TITLE
电脑小白不懂哎

### ISSUE THREAD

**Issue by Lamarjk** [cxOrz/chaoxing-sign-cli#34]
我把node和这个项目都下载了，但不知道要怎么办，不知道下一步是什么，没有找到npm starter在哪里

**Comment by Cherished-wish** [comment]
> 文档应该是很细了… 去打开命令提示符，用cd命令进到项目目录下，运行命令 `npm start`

请问用node输入克隆指令以后Uncaught SyntaxError：Unexpected identifier怎么办呢?

**Comment by cxOrz** [comment]
不是在node里运行克隆，不需要进入node交互环境。

![GIF](https://636c-cloudbase-1a4211-1252446325.tcb.qcloud.la/chaoxing-sign-cli/how-to-start.gif?)
