### ISSUE TITLE
请问如何才能运行在服务器端？

### ISSUE THREAD

**Issue by dcdq66** [cxOrz/chaoxing-sign-cli#35]
尝试一下午，最终结果也只能在本地运行，在服务器运行时不能通过（http://ip地址:端口）的方式访问到API界面和图形化界面，请问需要设置哪个文件才能实现呢

**Comment by cxOrz** [comment]
https://github.com/cxOrz/chaoxing-sign-ui/issues/2
https://github.com/cxOrz/chaoxing-sign-ui/issues/7
https://github.com/cxOrz/chaoxing-sign-ui/issues/8
https://github.com/cxOrz/chaoxing-sign-cli/issues/28
https://github.com/cxOrz/chaoxing-sign-cli/issues/21
https://github.com/cxOrz/chaoxing-sign-cli/issues/22

**Comment by cxOrz** [comment]
再检查检查服务器防火墙的设置，访问的端口要配置允许。

**Comment by dcdq66** [comment]
服务器策略组开放5000端口，修改chaoxing-sign-cli/src/serve.js内最后一行为：API Server: http://服务器IP:5000，以及chaoxing-sign-ui/src/api.js内第一行为：const baseUrl = 'http://服务器IP:5000'，最后访问http://服务器IP:5000还是不行

**Comment by dcdq66** [comment]
http://服务器IP:3000也不行

**Comment by cxOrz** [comment]
这我就不知道了，我这没法确定你那里是什么问题，再仔细检查检查吧

**Comment by nikKrian** [comment]
您好，在云上部署时如何实现后台持续运行呢，

**Comment by cxOrz** [comment]
> 您好，在云上部署时如何实现后台持续运行呢，

[pm2](https://pm2.keymetrics.io/)
