### ISSUE TITLE
身份过期，程序将关闭，请你使用手动填写用户名密码的方式登录！手动登录后身份信息刷新，之后可继续使用本地凭证！

### ISSUE THREAD

**Issue by nikKrian** [cxOrz/chaoxing-sign-cli#36]
身份过期，程序将关闭，请你使用手动填写用户名密码的方式登录！手动登录后身份信息刷新，之后可继续使用本地凭证！
请问这个是什么原因呢，手动登录也显示这个，是ip被封了吗

**Comment by cxOrz** [comment]
在服务器运行的吗，还是说在自己电脑是运行也是这样

**Comment by nikKrian** [comment]
> 

谢谢你，在服务器上，已经解决了，可能是同个ip登陆频繁了，很好用😁
