### ISSUE TITLE
记得改密码

### ISSUE THREAD

**Issue by Lakr233** [cxOrz/chaoxing-sign-cli#39]
~~我这有 `src/configs/storage.json`~~

**Comment by cxOrz** [comment]
那天不小心把这个文件也提交上去了，后来立马退回又强制推送了一次。没想到还是晚了哈哈哈。谢谢提醒 😄

**Comment by Lakr233** [comment]
once again...!!!

**Comment by cxOrz** [comment]
诶，前些天确实不小心推上去了密码。然后很快就回退版本，强推了一波。应该看不到了呀

**Comment by cxOrz** [comment]
改好了，感谢提醒😘

**Comment by Lakr233** [comment]
> 应该看不到了呀

我开了仓库镜像，因为感觉是高危项目随时会没所以本地备份了一份。然后收到提醒是说：

> Repository mirroring on mirrorbot/chaoxing-sign-cli has been paused due to too many failures. The last failure was:
> The default branch (main) has diverged from its upstream counterpart and could not be updated automatically.

坏笑（x

**Comment by cxOrz** [comment]
原来如此🥹
