### ISSUE TITLE
emmm无法使用了，直接报错

### ISSUE THREAD

**Issue by COOPER-ZiLie** [cxOrz/chaoxing-sign-cli#41]
确定是最新版本，提示报错。。。

![image](https://user-images.githubusercontent.com/77004704/170928408-9ec7e5cd-51a4-4f7a-92fe-7ccd331747d8.png)

**Comment by cxOrz** [comment]
你是不是没有任何课程

**Comment by cxOrz** [comment]
一切正常诶
![image](https://user-images.githubusercontent.com/32982052/170931355-9ee6fa5a-6768-42a3-ae65-bfb7e731258a.png)

**Comment by moxiaowk** [comment]
一切正常+1

**Comment by feizao67** [comment]
> 确定是最新版本，提示报错。。。
> 
> ![image](https://user-images.githubusercontent.com/77004704/170928408-9ec7e5cd-51a4-4f7a-92fe-7ccd331747d8.png)

maybe是nodejs的版本问题，我一开始也遇到类似报错，更新到>=12.16就解决了

**Comment by cxOrz** [comment]
> > 确定是最新版本，提示报错。。。
> > ![image](https://user-images.githubusercontent.com/77004704/170928408-9ec7e5cd-51a4-4f7a-92fe-7ccd331747d8.png)
> 
> maybe是nodejs的版本问题，我一开始也遇到类似报错，更新到>=12.16就解决了

你这个确实是版本问题，Object.fromEntries是ES10新增的，不能用太老版本的Node。

楼主的问题看起来是没加入课程，或者课程里至少一个签到活动都没有，所以activeList是null 🤣
