### ISSUE TITLE
请问可以通过api直接签到吗

### ISSUE THREAD

**Issue by moxiaowk** [cxOrz/chaoxing-sign-cli#42]
请问可以通过api直接签到吗，就是类似于这样一个链接http://你的域名/sign?account=账号&password=密码**********，直接调用api签到

**Comment by cxOrz** [comment]
可以， 参考这里https://github.com/cxOrz/chaoxing-sign-cli#%E8%BF%90%E8%A1%8C%E6%8E%A5%E5%8F%A3%E6%9C%8D%E5%8A%A1

**Comment by moxiaowk** [comment]
![image](https://user-images.githubusercontent.com/62387130/170934009-f0d8db64-cfdb-4730-b4d9-1279f1076fab.png)
大佬，可以给个URL请求的示范吗，不咋会搞www

**Comment by cxOrz** [comment]
POST https://xxxxx/login HTTP/1.1
Content-Type: application/json

{
  "phone": "123456789",
  "password": "abcd1234"
}

**Comment by cxOrz** [comment]
fid 在cookie里能找到，也叫做spaceFid，是学校代码
