### ISSUE TITLE
关于部署服务端问题

### ISSUE THREAD

**Issue by weiyunwl** [cxOrz/chaoxing-sign-cli#43]
请问老大怎么联系，我部署了很久没有成功，或者有没有现成的api可以使用。

**Comment by cxOrz** [comment]
写的挺详细了，每一步都写出来了，哪一步没弄出来说一下~
[云函数部署](https://github.com/cxOrz/chaoxing-sign-cli#%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5)
