### ISSUE TITLE
调用/activity接口传入四个必要的参数之后返回状态码200

### ISSUE THREAD

**Issue by gongjiageng** [cxOrz/chaoxing-sign-cli#44]
调用/activity接口传入四个必要的参数之后返回状态码200，但是我输出请求内容确实这样，需要授权。是什么问题呢
![image](https://user-images.githubusercontent.com/78600910/171017987-bdc45880-10d2-4853-88b8-912e83eed328.png)

**Comment by gongjiageng** [comment]
![image](https://user-images.githubusercontent.com/78600910/171021017-59c1d01a-bd93-4033-8f03-ed35982bd052.png)
我是这样写的

**Comment by cxOrz** [comment]
uid小写
![image](https://user-images.githubusercontent.com/32982052/171021156-e17dcb2c-00e1-4eb2-bb68-2ad81fde9141.png)

**Comment by gongjiageng** [comment]
等我研究研究怎么传入json格式的，有点不会

**Comment by moxiaowk** [comment]
请问fid是啥，哪个接口可以获取，谢谢
