### ISSUE TITLE
关于部署https服务端

### ISSUE THREAD

**Issue by feizao67** [cxOrz/chaoxing-sign-cli#45]
你好！我正在尝试使用宝塔搭建那个超星打卡后端与前端ui配合，并且在http的情况下搭建成功，
但是当我开启https后开始无法正常工作，‍请问我在ui端的src/config/api.js 更改为https之后，cli端还要做什么修改吗，
等完全搭建完成后我写一个在宝塔面板的搭建教程吧，不胜感激！

**Comment by moxiaowk** [comment]
重新打包build一下，然后运行就行了

**Comment by moxiaowk** [comment]
api可以用反代，反代的域名加ssl

**Comment by cxOrz** [comment]
楼上正解，用Nginx把对应的https请求代理到http

**Comment by moxiaowk** [comment]
宝塔面板示例
![B6581CDFB8CD929CCA9181EAEFC14AE7](https://user-images.githubusercontent.com/62387130/171030233-034c3c39-fed2-4f22-aa59-a3af0586e9b0.jpg)
![79B1B854DEBFB4C5C10832CF4706433A](https://user-images.githubusercontent.com/62387130/171030450-dcba56bc-d704-4086-942a-e5ea47f8744e.jpg)

**Comment by feizao67** [comment]
已成功搭建！感谢！

**Comment by feizao67** [comment]
我尝试将反向代理设置成使用目录代理，如图：
![image](https://user-images.githubusercontent.com/37013075/171183085-b2748d6d-b2af-4fcf-896d-738a12ea5fcc.png)
现访问https://xxt.xxx.com能访问到"已经修改好api.js，其内容为https://xxt.xxx.com/api，而yarn build的前端页面"，如图：
![image](https://user-images.githubusercontent.com/37013075/171184761-89be94dd-a607-43da-afda-e0d361b6e6cd.png)
访问https://xxt.xxx.com/api能访问到Welcome, chaoxing-sign-cli API service is running.如图：
![image](https://user-images.githubusercontent.com/37013075/171184876-29de3c8e-c15d-41f6-9168-e06991fa1339.png)
但是网页发起的登陆请求却返回404，如图：
![image](https://user-images.githubusercontent.com/37013075/171184604-b618d673-f184-4d24-9e61-ea05e04eafe4.png)
请问大佬这是什么原因造成的，有没有什么解决方法（我已经各种google尝试解决好久了T_T）

**Comment by cxOrz** [comment]
我猜测是反向代理没设置对...，不太清楚 :(

@moxiaowk hxd来帮他看看呗。

**Comment by moxiaowk** [comment]
感觉大概率是后端api运行不稳定吧，你试试看前端登录失败后再访问api接口试试看，如果先运行接口，访问正常，然后登录失败，然后直接访问接口url，返回的数据不是Not Found而是接口404的话，就是我所说的这个问题

解决方法是使用screen以保持后端接口的稳定运行

**Comment by feizao67** [comment]
感谢解疑！
screen的操作还是理解的，上述提问时的后端已经是运行在screen上了，
可以确定后端是稳定运行的（并且直接访问http://我机器的ip:5000/login等接口也是一切正常的）
就是访问https://做好反代的域名/api/login这种方式会出现异常

**Comment by moxiaowk** [comment]
那我不知道了，不过我的是没有/api/的，不知道是不是有影响

**Comment by cxOrz** [comment]
实在不行就用腾讯的云开发+云函数吧，最佳实践~

**Comment by feizao67** [comment]
好的！感谢两位大佬！:)
