### ISSUE TITLE
API服务端鉴权+不允许跨域

### ISSUE THREAD

**Issue by moxiaowk** [cxOrz/chaoxing-sign-cli#47]
大佬可以加个鉴权之类的吗，把api后端设置成只能限制的域名访问或请求，这样可以设置成只有前端域名或自己设置的域名可以用，防止网站被抓包滥用自己的api

还有单位时间ip的访问次数，防止服务器负载过大和滥用

**Comment by cxOrz** [comment]
把允许跨域的代码删除即可，在serve.js中。

这一部分：
```
app.use(async (ctx, next) => {
  ctx.set("Access-Control-Allow-Origin", "*")
  ctx.set("Access-Control-Allow-Headers", "Content-Type")
  await next()
})
```

**Comment by cxOrz** [comment]
> 好的，谢谢大佬。这个跨域删除了之后是只有本服务器的域名可以访问吗

是的~

**Comment by moxiaowk** [comment]
好的，谢谢

**Comment by moxiaowk** [comment]
大佬，刚刚测试了下，如果这个网址填了别的地方，前端确实显示跨域，用不了签到。但是当写了前端网址，我使用宝塔搭建另一个网站通过写PHP直接调用后端的接口却没有跨域拦截（本服务器和其他服务器都测试了）

**Comment by cxOrz** [comment]
> 大佬，刚刚测试了下，如果这个网址填了别的地方，前端确实显示跨域，用不了签到。但是当写了前端网址，我使用宝塔搭建另一个网站通过写PHP直接调用后端的接口却没有跨域拦截（本服务器和其他服务器都测试了）
> 
> 莫非只能阻止其他搭建的前端对接该后端，无法拦截直接调用后端却跨域的请求嘛

对的，所以我用Nodejs写这个项目，直接请求学习通的接口，拦不下来

**Comment by cxOrz** [comment]
想要只能自己用的话，也有办法，写个中间件。自己设个密码，请求中带上这个密码，让接口服务判断，如果不带这个密码就返回无权访问。这个密码只有自己知道，别人不知道。

```js
app.use(async (ctx, next) => {
  if (ctx.header.authorization !== 'a1b2c3mypwd') {
    ctx.body = '无权访问'
  }
  await next()
});
```
请求时，请带上这个 `Authorization` 请求头，值为密码。

这个中间件可以写在刚刚的跨域中间件的下方

**Comment by moxiaowk** [comment]
$header= array( 'Content-Type: application/json;charset=UTF-8&authorization: xxx')如果需要直接请求api的请求头，是这样写吧

加上去后  前端也需要改吧?应该在哪里改呢

**Comment by cxOrz** [comment]
前端的代码里全部是用axios请求的，改为类似下面的代码
```js
await axios.post(activity_api, {
      uf: userParams.uf,
      _d: userParams._d,
      vc3: userParams.vc3,
      uid: userParams._uid
    }, {headers: {
      'Authorization': 'xxxxx'
    }})
```

**Comment by moxiaowk** [comment]
不知道哪里有这些请求
![027A0C58](https://user-images.githubusercontent.com/62387130/171195852-5ba459de-0413-4f6c-8a6e-23b3cc2eb4ae.gif)

**Comment by cxOrz** [comment]
在 Start.js, DashBoard.js 中都有类似这种，搜索一下 axios关键字，应该可以查到每一个用到的地方，逐个改一下就好了。
不过建议先别急，我正在升级项目，改用ts写，代码可能有些变动

![image](https://user-images.githubusercontent.com/32982052/171196359-1ab9f62e-b5b8-4e7a-a786-3fcea9a99bab.png)

**Comment by moxiaowk** [comment]
![0BABDCF166C5EEBAF3CEE361CF70FDD3](https://user-images.githubusercontent.com/62387130/171205638-fc2020d0-2cae-42fe-bea8-3875cbb6c786.jpg)
奇怪，设置了还是不行啊

![1BFBA5D5BAC230458034BFEF060BF496](https://user-images.githubusercontent.com/62387130/171206432-522c3aed-daca-4bb5-9706-e2c026cfdcc5.jpg)

![68F13E0A5D4F37DD2C0934484990B1A2](https://user-images.githubusercontent.com/62387130/171206474-b43a204f-2463-4b50-8a93-db311e8d2982.jpg)

仅仅是浏览器访问URL不能直接访问了而已

**Comment by cxOrz** [comment]
代码改为：
```js
app.use(async (ctx, next) => {
  if (ctx.header.authorization !== '123456') {
    ctx.body = '无权访问'
    return
  } else await next()
});
```

**Comment by moxiaowk** [comment]
可以了，不过前端访问不了了


`    }, {headers: {
      'Authorization': 'xxxxx'
    }})`


是用的这个，不知道哪里有问题

**Comment by cxOrz** [comment]
我忘添加允许 Authorization 请求头了... 
跨域那部分代码，改成这样：
```js
app.use(async (ctx, next) => {
  ctx.set("Access-Control-Allow-Origin", "*")
  ctx.set("Access-Control-Allow-Headers", "Content-Type")
  ctx.set("Access-Control-Allow-Headers", "Authorization")
  await next()
})
```

**Comment by cxOrz** [comment]
今晚有点晕乎，写代码写傻了。刚把UI仓库更新~

**Comment by cxOrz** [comment]
卧槽了我真是啥b了。脑子昏了。。应该写在一条里面的。

```js
app.use(async (ctx, next) => {
  ctx.set("Access-Control-Allow-Origin", "*")
  ctx.set("Access-Control-Allow-Headers", "Content-Type, Authorization")
  await next()
})
```
睡觉！

**Comment by moxiaowk** [comment]
不过更新后写法貌似要变化？报错如下

ERROR in ./src/pages/DashBoard/DashBoard.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /www/wwwroot/000.cn/chaoxing-sign-ui-main/src/pages/DashBoard/DashBoard.tsx: Unexpected token (64:4)

  62 |     }, {headers: {
  63 |       'Authorization: 000'
> 64 |     }})
     |     ^
  65 |     console.log(activity.data)
  66 |     setProgress(false)
  67 |     if (activity.data === 'NoActivity') {
    at instantiate (/www/wwwroot/000.cn/chaoxing-sign-ui-main/node_modules/@babel/parser/lib/index.js:72:32)
    at constructor (/www/wwwroot/000.cn/chaoxing-sign-ui-main/node_modules/@babel/parser/lib/index.js:358:12)
    at Object.raise (/www/wwwroot/000.cn/chaoxing-sign-ui-main/node_modules/@babel/parser/lib/index.js:3334:19)
    at Object.unexpected (/www/wwwroot/000.cn/chaoxing-sign-ui-main/node_modules/@babel/parser/lib/index.js:3372:16)
    at Object.parseObjPropValue (/www/wwwroot/000.cn/chaoxing-sign-ui-main/node_modules/@babel/parser/lib/index.js:13688:21)
    at Object.parseObjPropValue (/www/wwwroot/000.cn/chaoxing-sign-ui-main/node_modules/@babel/parser/lib/index.js:10576:11)
    at Object.parsePropertyDefinition (/www/wwwroot/000.cn/chaoxing-sign-ui-main/node_modules/@babel/parser/lib/index.js:13604:10)
    at Object.parseObjectLike (/www/wwwroot/000.cn/chaoxing-sign-ui-main/node_modules/@babel/parser/lib/index.js:13494:21)
    at Object.parseExprAtom (/www/wwwroot/000.cn/chaoxing-sign-ui-main/node_modules/@babel/parser/lib/index.js:12889:23)
    at Object.parseExprAtom (/www/wwwroot/000.cn/chaoxing-sign-ui-main/node_modules/@babel/parser/lib/index.js:8033:20)
 @ ./src/index.tsx 10:0-52 36:38-47

ERROR in src/pages/DashBoard/DashBoard.tsx
  Line 64:4:  Parsing error: ':' expected

webpack 5.71.0 compiled with 2 errors in 42542 ms
ERROR in src/pages/DashBoard/DashBoard.tsx:64:5
TS1005: ':' expected.
    62 |     }, {headers: {
    63 |       'Authorization: 000'
  > 64 |     }})
       |     ^
    65 |     console.log(activity.data)
    66 |     setProgress(false)
    67 |     if (activity.data === 'NoActivity') {

ERROR in src/pages/DashBoard/DashBoard.tsx:85:5
TS1005: ':' expected.
    83 |     }, {headers: {
    84 |       'Authorization: 000'
  > 85 |     }})
       |     ^
    86 |     return result.data
    87 |   }
    88 |   const photoSign = async (objectId: string) => {

ERROR in src/pages/DashBoard/DashBoard.tsx:100:5
TS1005: ':' expected.
     98 |     }, {headers: {
     99 |       'Authorization: 000'
  > 100 |     }})
        |     ^
    101 |     return result.data
    102 |   }
    103 |   const qrcodeSign = async (enc: string) => {

ERROR in src/pages/DashBoard/DashBoard.tsx:115:5
TS1005: ':' expected.
    113 |     }, {headers: {
    114 |       'Authorization: 000'
  > 115 |     }})
        |     ^
    116 |     return result.data
    117 |   }
    118 |   const locationSign = async (lat: string, lon: string, address: string) => {

ERROR in src/pages/DashBoard/DashBoard.tsx:132:5
TS1005: ':' expected.
    130 |     }, {headers: {
    131 |       'Authorization: 000'
  > 132 |     }})
        |     ^
    133 |     return result.data
    134 |   }
    135 |

ERROR in src/pages/DashBoard/DashBoard.tsx:288:5
TS1005: ':' expected.
    286 |     }, {headers: {
    287 |       'Authorization: 000'
  > 288 |     }})
        |     ^
    289 |     return token.data._token
    290 |   }
    291 |   const uploadFile = async (inputFile: File, token: string) => {

ERROR in src/pages/DashBoard/DashBoard.tsx:328:11
TS1005: ':' expected.
    326 |           }, {headers: {
    327 |             'Authorization: 000'
  > 328 |           }})
        |           ^
    329 |           if (res.data === 'AuthFailed') {
    330 |             setAlert({ msg: '重新登录失败', show: true, severity: 'error' })
    331 |           } else {

**Comment by cxOrz** [comment]
写的不对，不是 ` 'Authorization: 000'` ，是 ` 'Authorization': '000'`
![image](https://user-images.githubusercontent.com/32982052/171305750-295e290b-184b-4cac-9f9a-358f3f951e4a.png)

**Comment by moxiaowk** [comment]
😘欧克，完美解决😍

**Comment by moxiaowk** [comment]
大佬，今天闲着抓包了一下网页来验证安全性的，发现一个安全性问题，使该方案失效😭
理论上原本跨域规则改了后是别的前端无法对接api，直接调用无法阻止
后面修改后理论上都能阻止，但是由于大佬的前端UI是直接调用的后端，也就是相当于用户直接post了，导致在前端加入的Authorization会直接暴露在用户面前，只要一抓包就可清楚看见Authorization的值从而失去安全性🤕【或许可以考虑将前端作为中转而非直接调用后端，用户提交到前端，前端中转再提交到后端(这样鉴权就全是前端中转与后端之间了，而不会暴露出来🤡)】
![E009704C07528D3C4225AD3710FD1F23](https://user-images.githubusercontent.com/62387130/172758905-4341b03b-460a-4802-b7eb-5024084ab9a2.jpg)

**Comment by cxOrz** [comment]
前端一切都是暴露出来的，只要用户要通过前端和后端交互，无论经过什么中转还是加密，都在浏览器进行，一切都能被看到。

想要别人无法调用你的接口，可以限定IP地址，比如在公司内网才能访问某些服务。其他什么转发、加一些特征字段来鉴权，都是只能增加接口被别人调用的难度，没有办法避免。这个项目，就是模拟了浏览器对学习通接口请求，再怎么转发再怎么加密字段，都是代码写出来的，都能照着模拟出来，没有办法阻止。

**Comment by moxiaowk** [comment]
嗯呢，谢谢大佬

**Comment by moxiaowk** [comment]
监听新增加的地方也要修改吧，请问这里应该在哪里修改😘
![image](https://user-images.githubusercontent.com/62387130/183262396-27e322c1-94e0-4e58-9f05-76050a0c1e68.png)
![image](https://user-images.githubusercontent.com/62387130/183262407-d184dd6c-a0f0-4477-b447-0b2f175c43cb.png)

**Comment by cxOrz** [comment]
和之前一样，写在axios最后一个参数。

**Comment by moxiaowk** [comment]
酱紫改？☺️
![L7)ABD9~9{Y0CYBPZ~JXJ`I_Mosaic_15_19_51](https://user-images.githubusercontent.com/62387130/183279901-c6481d7d-3e4f-4d7a-ae82-1a12dc5f2e84.png)
![(E1ASPY PF_ 6S~RK_W1Q$1(1)_Mosaic_15_19_28](https://user-images.githubusercontent.com/62387130/183279903-92525cab-4c23-4421-981f-971a6e4a8034.png)

**Comment by cxOrz** [comment]
是的 🍡

**Comment by cxOrz** [comment]
[Nginx 限制IP访问频率](https://www.w3cschool.cn/nginxsysc/nginxsysc-limit-req.html)
[Nginx 允许或禁止某个IP地址或网段](https://blog.51cto.com/niuben/3027885)
