### ISSUE TITLE
大佬，这个upload怎么用，我这样写报错

### ISSUE THREAD

**Issue by gongjiageng** [cxOrz/chaoxing-sign-cli#48]
![image](https://user-images.githubusercontent.com/78600910/171169201-795cf657-8e39-4a05-9b7e-791a91cb76f7.png)
![8D4DB32E5E106806C208D3B92602547F](https://user-images.githubusercontent.com/78600910/171169266-bef5ffa5-dfee-4dee-a029-0735dc2c4313.jpg)
![Uploading image.png…]()

**Comment by cxOrz** [comment]
接口的说明我没详细写，造成误解了 🤣 ，这个`_token`前面加了个 `?` 想表达的意思是，这个 `_token` 是一个URL参数，是在请求地址后面的例如 `http://xxxxx.com/upload?_token=xxxxxxx`。

然后这个请求是POST请求，Content-Type 是 multipart/form-data 类型的。

**Comment by gongjiageng** [comment]
![image](https://user-images.githubusercontent.com/78600910/171213316-60fc16f0-0ccb-4db7-a481-3393210d6d89.png)
![image](https://user-images.githubusercontent.com/78600910/171213485-7c3a2b74-90c5-4a18-8861-4a6d407ade6d.png)
这个现在bu不报错了，但是也没啥响应，除了那个token都是以表单的形式提交吗，还是只有那个图片是以表单的形式

**Comment by cxOrz** [comment]
file(图片)、uf、vc3、uid、_d全部添加到表单里，_token写在URL后面。
