### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by Meteorsss** [cxOrz/chaoxing-sign-cli#49]
之前一直使用正常，今天登录一直显示登录失败，用的安卓termux

**Comment by cxOrz** [comment]
更新了吗宝

**Comment by Meteorsss** [comment]
输入命令后不是会自动更新么？后来还是失败，我就把termux清楚数据重新安装了，然后就可以了，但是签到时间也过了X﹏X

**Comment by moxiaowk** [comment]
将在每次签到结束强制拉取代码更新，没签到成功就没有更新🤣 @Meteorsss

**Comment by cxOrz** [comment]
运行失败也会更新的，只不过网络状态不好的情况下大概率更新失败。

**Comment by Meteorsss** [comment]
> 将在每次签到结束强制拉取代码更新，没签到成功就没有更新🤣 @Meteorsss

那怎么强制更新啊？

**Comment by Meteorsss** [comment]
> 运行失败也会更新的，只不过网络状态不好的情况下大概率更新失败。

网络没问题，开梯子了

**Comment by Meteorsss** [comment]
> 运行失败也会更新的，只不过网络状态不好的情况下大概率更新失败。

网络没问题，开代理了，那能强制手动更新么？
