### ISSUE TITLE
关于开发计划:大佬是否考虑使用IM协议监测签到活动

### ISSUE THREAD

**Issue by moxiaowk** [cxOrz/chaoxing-sign-cli#50]
关于开发计划:大佬是否考虑使用IM协议监测签到活动，该方案的优点在于通过监测学习通所使用的IM通讯协议服务商环信（学习通通讯服务商）在app或wab情况下发送的消息通知（即使用IM协议构建的消息框架和关键内容），当签到通知发送，程序监测到了该消息框架然后可以进行签到。不同于主动访问学习通的签到api（避免了高频访问所导致的黑ip问题），只是被动收到才运行签到进。可以减少服务器的大量请求，因为只需要登录，然后没有监测到关键消息就处于静置的状态。

**一 、环信与学习通关系**

_1.1 对学习通签到通知抓包显示了环信网址_

![401455AA44C790096B5337568764ABD7](https://user-images.githubusercontent.com/62387130/171410945-ab69a783-cd03-4a8c-b12f-1857c53f3fd5.jpg)

![CB79239AD48AF495E7D232A36E097419](https://user-images.githubusercontent.com/62387130/171410972-f7d964bd-a9dd-4c4d-9f5d-65a979078aa2.jpg)

_1.2 环信与学习通关于IM即时通讯云合作的资讯_

https://www.easemob.com/news/4082

**二 、关于IM协议监听学习通消息并处理，可参考资料如下**

_2.1 环聊开发文档关于学习通所使用IM消息构建及框架_

https://docs-im.easemob.com/im/web/basics/message

_2.2 监听消息_

https://github.com/cyanray/cx-auto-sign/blob/37b28b0011c9f6ca8224fd51164d56e1e3669a08/cx-auto-sign/WorkCommand.cs#L82

_2.3 处理环信消息_

https://github.com/Clansty/superstar-checkin/blob/main/handlers/handleEasemobMessage.ts

_2.4 判断消息_

2.4.1 判断一个 atype=0 的消息是不是变相的签到消息

https://github.com/Clansty/superstar-checkin/commit/4066f827349904566cb006688e33e929cfaed998#diff-bbf0d02ebcf6764cae92fa4045a2d6f15f8a479cd1aa2ab4d1fd435a3aa74bbd

2.4.3 处理

https://github.com/cyanray/cx-auto-sign/blob/master/cx-auto-sign/Cxim.cs

2.4.4 对消息Tuid适配

https://github.com/cyanray/cx-auto-sign/pull/34/commits/fce78fba0e47dee9b04b41d3de9b0813c90a5eec

_2.5 接收后签到_

https://github.com/cyanray/cx-auto-sign/pull/3/commits/69c033de357164f54618828ca28971e8160a0672

暂时找到这些，有的归类可能并不完善，因为一个文件可能实现了不止一个功能☺，大佬有考虑嘛？就问问，感觉这种方式貌似比主动请求好些

**Comment by cxOrz** [comment]
IM协议：
- 监听消息，消耗资源少
- 不容易被判异常IP
- 实现较困难

当前方式：
- 随时主动地查询活动
- 不存在漏接收的情况

现在的方式是遍历，但根据实际情况来看，会有签到的课程总是在前几个，绝大多数情况下检测到一个有效签到，请求次数是个位数（假如前五门课程会发布签到，最多5次请求就可判断出有效签到），处于完全可以接受的范围内，难以被判异常IP地址。且主动查询，不会漏掉任何活动，特殊情况下一次或多次没签上可以再次主动查询。暂时，我觉得传统方法是非常合适的。

**Comment by moxiaowk** [comment]
嗯呢😘

**Comment by moxiaowk** [comment]
学习通环信IM协议研究的资料

https://uint128.com/2020/11/16/%E8%B6%85%E6%98%9F%E5%AD%A6%E4%B9%A0%E9%80%9AIM%E5%8D%8F%E8%AE%AE%E5%88%86%E6%9E%90/

**Comment by cxOrz** [comment]
预告：新功能即将来临~

~~从中午一屁股坐到现在没怎么动弹，快要死了~~

**Comment by cxOrz** [comment]
已实现 :laughing:

**Comment by moxiaowk** [comment]
牛蛙牛蛙
