### ISSUE TITLE
二维码识别请求成功，但是识别失败

### ISSUE THREAD

**Issue by gongjiageng** [cxOrz/chaoxing-sign-cli#51]
![image](https://user-images.githubusercontent.com/78600910/171587096-83f598af-5137-435f-8416-7e9b110ca7cb.png)

**Comment by cxOrz** [comment]
如需配置使用 [腾讯云OCR](https://console.cloud.tencent.com/ocr/overview) 以精准解析二维码，请解压并在 env.json 配置腾讯云的 secretId 和 secretKey

**Comment by cxOrz** [comment]
这个 `/qrocr` 是专门调用腾讯的智能扫描接口的，默认情况下二维码识别是在浏览器本地进行，用不到接口。
