### ISSUE TITLE
部署在服务器上一直出现跨域问题

### ISSUE THREAD

**Issue by YxinMiracle** [cxOrz/chaoxing-sign-cli#53]
![image](https://user-images.githubusercontent.com/56109594/171782287-3d745f6d-1a96-474c-8a36-5c50d6c31c8f.png)

**Comment by cxOrz** [comment]
https://github.com/cxOrz/chaoxing-sign-ui#%E9%85%8D%E7%BD%AE

**Comment by YxinMiracle** [comment]
> https://github.com/cxOrz/chaoxing-sign-ui#%E9%85%8D%E7%BD%AE
修改了 也不可以

**Comment by cxOrz** [comment]
修改了，真的可以。

防火墙对应端口开了没有；修改完配置有没有重新构建好部署上去；部署好会不会因为浏览器缓存，还没生效，清理一下缓存；

按照说明部署，完全不会有问题；
