### ISSUE TITLE
搭配云函数使用后数据获取出现问题，能够成功登录但是获取不到名字，登录后也不可以进行签到

### ISSUE THREAD

**Issue by YxinMiracle** [cxOrz/chaoxing-sign-cli#54]
![image](https://user-images.githubusercontent.com/56109594/171785193-93c8c262-dda1-48fb-af22-ce4d9af64f3d.png)

**Comment by cxOrz** [comment]
没有获取到名字：会不会是你没设定用户名，这是不是新注册的账号用来测试的。

不可以进行签到：现在是否有签到活动，没有签到活动就没到可签。

**Comment by YxinMiracle** [comment]
不是, 是不管输入什么账号都能成功进行登录
![image](https://user-images.githubusercontent.com/56109594/171785503-708269d9-8884-45c9-9ee8-24318908ad79.png)

**Comment by cxOrz** [comment]
一切正常
![image](https://user-images.githubusercontent.com/32982052/171785898-93a631f8-9bb9-4d00-980c-294cb2687354.png)

**Comment by YxinMiracle** [comment]
重新配置云函数后报错
![image](https://user-images.githubusercontent.com/56109594/171786563-e7583440-c582-4e96-a765-6033479a405f.png)

**Comment by cxOrz** [comment]
要求至少Nodejs版本大于 12.16
![image](https://user-images.githubusercontent.com/32982052/171786688-c9145484-faf5-4454-95c4-702303f55760.png)

**Comment by cxOrz** [comment]
仔细看看文档哥

**Comment by YxinMiracle** [comment]
> 仔细看看文档哥
感谢！！！麻烦了
