### ISSUE TITLE
关于腾讯云函数更改策略的事

### ISSUE THREAD

**Issue by Memorz** [cxOrz/chaoxing-sign-cli#55]
腾讯云已于6月1日更改云函数计费策略，总体意思就是前三个月免费白嫖，然后从第四个月开始就必须付费，阿里云目前关于云函数依旧是每月都有免费额度，大佬有考虑过出个阿里云函数的吗？

**Comment by cxOrz** [comment]
Serverless的云函数是这样的，但是这边用的是云开发里的云函数，依旧免费。
![image](https://user-images.githubusercontent.com/32982052/171874987-681667c5-b3d9-4201-9118-ed28aa93a036.png)

**Comment by Memorz** [comment]
懂了   谢大佬
