### ISSUE TITLE
大佬php

### ISSUE THREAD

**Issue by xuezheli** [cxOrz/chaoxing-sign-cli#56]
用PHP提交签到，为啥一直提示非法请求呀大佬，应该不是php的问题应该是少提交了什么参数，但是接口都是按照大佬文件里面 的接口呀

**Comment by cxOrz** [comment]
签到前，应该先提交预检请求。在 activity.js 里有个 `preSign`

**Comment by xuezheli** [comment]
好的谢谢大佬
