### ISSUE TITLE
运行命令 npm start出现问题。

### ISSUE THREAD

**Issue by Sneverend** [cxOrz/chaoxing-sign-cli#57]
![image](https://user-images.githubusercontent.com/26741299/176135737-2bfe4df7-e898-4590-933b-88be70c34937.png)

**Comment by cxOrz** [comment]
把代理关了。应该就好了，网络问题。

**Comment by Sneverend** [comment]
新手小白,麻烦各位大神指点。谢谢。

**Comment by Sneverend** [comment]
> > 把代理关了。应该就好了，网络问题。
> 
> 谢谢。我试一下。

大神，还是这样。

**Comment by cxOrz** [comment]
我这试了下一切正常。换个网络环境试试看吧。

**Comment by Sneverend** [comment]
> 我这试了下一切正常。换个网络环境试试看吧。

可以了，谢谢您。非常感谢。

**Comment by Sneverend** [comment]
> 不用支持我 😂😂，默默用就行

大神，我已经关注您了。我可能不经常上线，不过以后时间还长，说不定能帮上忙。
