### ISSUE TITLE
获取不到用户名

### ISSUE THREAD

**Issue by moxiaowk** [cxOrz/chaoxing-sign-cli#58]
![image](https://user-images.githubusercontent.com/62387130/179355731-8ce49e92-bb81-4642-b617-5053b00fe38d.png)
很奇怪，拿自己注册的小号获取不到用户名，大号可以

**Comment by cxOrz** [comment]
小号没有实名认证+绑定学校，都是这样我也是

**Comment by moxiaowk** [comment]
嗯，应该是这样
