### ISSUE TITLE
功能建议：大佬是否考虑使IM监听模式与api接口服务同时运行

### ISSUE THREAD

**Issue by moxiaowk** [cxOrz/chaoxing-sign-cli#62]
功能建议：大佬是否考虑使IM监听模式与api接口服务同时运行

我们可以设想第四种模式
![image](https://user-images.githubusercontent.com/62387130/183119616-731b0d3f-f03c-495b-8691-c84723ce1de3.png)

使用该指令(第四种)后会将程序形成两个工作分区，原本的接口和额外的监听模式分区（使IM监听模式与api接口服务同时运行），前端可以加个加入监听的按钮（例如初始灰色按钮），点击该按钮后会将账户添加至监听分区（然后变为绿色），不需要的时候再次点击可以使之从监听分区中删除该账户（然后按钮会变回灰色）

【正常添加账户应该在接口的分区，然后点按钮会复制到监听分区】

前端无需大的改变，只需右上角加个监听的小按钮（初始颜色），点击后监听（变一个颜色），再点击就取消监听（回到初始颜色）即可

![1D9973C32389761136A72F9E2F68FCF6](https://user-images.githubusercontent.com/62387130/183121089-e14c7fb4-ce75-42d4-b71e-3dc8eb792a6b.jpg)

**Comment by cxOrz** [comment]
建议不错:D
最近较忙，有空了就实现

**Comment by moxiaowk** [comment]
🤩嘿嘿，还是大佬牛

**Comment by o0Lev1s0o** [comment]
🌹🌹🌹

**Comment by cxOrz** [comment]
https://github.com/cxOrz/chaoxing-sign-cli/commit/ddb967dbecd02f873840a7367fe2c26fa2c08515 已实现

**Comment by moxiaowk** [comment]
牛蛙牛蛙
