### ISSUE TITLE
监听模式无法运行

### ISSUE THREAD

**Issue by o0Lev1s0o** [cxOrz/chaoxing-sign-cli#63]
监听中后随即进程被终止，请求大佬指点

**Comment by cxOrz** [comment]
加个q，借用下账号看看什么问题

**Comment by o0Lev1s0o** [comment]
897071265

**Comment by cxOrz** [comment]
- https://github.com/cxOrz/chaoxing-sign-cli/commit/b9b08270f848b8f1434afda358b6ffe34b06f05d 修改JSON内容的判定界限
- https://github.com/cxOrz/chaoxing-sign-cli/commit/ab1fba0defdc63e040bf7c052f493ba7ebde62e6 尝试2种方式登录；修改签到判断方式
