### ISSUE TITLE
监听模式下  新签到活动  未签到

### ISSUE THREAD

**Issue by moxiaowk** [cxOrz/chaoxing-sign-cli#64]
![image](https://user-images.githubusercontent.com/62387130/183283363-f9847538-8faa-4427-914a-0e41479e2ecd.png)
此时已启用监听模式，但并未签到
![969D5052C90E9052BF57DD35A9E77595](https://user-images.githubusercontent.com/62387130/183283448-abba1b88-f577-4038-88fc-3d877b174844.jpg)

**Comment by cxOrz** [comment]
加个Q，细说

**Comment by moxiaowk** [comment]
Q  2094797663
