### ISSUE TITLE
有点不太懂这个二维码签到enc 参数填在哪

### ISSUE THREAD

**Issue by sxceocom** [cxOrz/chaoxing-sign-cli#67]
有点不太懂这个二维码签到enc 参数填在哪
![Q}CR5OPI`0~HDK016MP6 U0](https://user-images.githubusercontent.com/86223309/185834004-3d27cf0f-07d4-4e5f-90e9-1c60dc427ec4.png)

**Comment by cxOrz** [comment]
![image](https://user-images.githubusercontent.com/32982052/185834107-a33d6a6f-08c7-44f6-bdb3-9a71db06a081.png)

自动不支持二维码签到

**Comment by cxOrz** [comment]
需要用手动的。通过 npm start 可以，或者用接口+签到UI项目也可以
