### ISSUE TITLE
监控端会自动掉

### ISSUE THREAD

**Issue by sxceocom** [cxOrz/chaoxing-sign-cli#69]
每天10点多就发现不自动监控了  不知道为啥要重新启动一下那个监控的API

**Comment by cxOrz** [comment]
建议一次监听不要超过5小时，毕竟用的websocket连太长时间也容易引起嫌疑，或会被自动断开。

**Comment by cxOrz** [comment]
有需要了，开一下，用完及时停止。

**Comment by sxceocom** [comment]
有没有办法就是说定时能开启的

**Comment by cxOrz** [comment]
DIY吧，用cron定时执行命令

**Comment by NANYUA** [comment]
定时执行命令但是要输入账号密码怎么办啊

**Comment by cxOrz** [comment]
可以把账号密码写死在代码里，monitor.ts

**Comment by NANYUA** [comment]
这个监听挂上以后能保持多久啊，早上起不来，只能晚上把他打开

**Comment by cxOrz** [comment]
这还真没试过，我现在挂上，看看什么时候掉。

**Comment by cxOrz** [comment]
13小时过去了，依然没掉

**Comment by NANYUA** [comment]
那定时启动怎么弄的啊，大佬

**Comment by cxOrz** [comment]
https://www.runoob.com/w3cnote/linux-crontab-tasks.html

**Comment by NANYUA** [comment]
这个启动以后是会自动关闭监听还是定时启动以后就挂着呢

**Comment by cxOrz** [comment]
启动会一直挂着，每25秒都会收到服务器的一个心跳包。只有出错或者手动关闭，才会停

**Comment by NANYUA** [comment]
好，谢谢大佬了
