### ISSUE TITLE
功能建议：大佬能不能写个接入邮件或者方糖呢签到成功和失败都会发邮件提醒

### ISSUE THREAD

**Issue by q2929843202** [cxOrz/chaoxing-sign-cli#72]
![微信图片_20220901165435](https://user-images.githubusercontent.com/97284858/187874311-e837343d-8c1d-43d5-80dd-05005e1829d7.jpg)
类似于这种
以及关于前端UI  能不能添加个删除用户的功能

**Comment by cxOrz** [comment]
右键卡片，删除用户

**Comment by q2929843202** [comment]
> 右键卡片，删除用户

在edge下 右键不能删除用户 也没有这个选项 不知道是不是我的问题
![image](https://user-images.githubusercontent.com/97284858/187880225-16e642e2-c08a-4922-817a-4847af3183f3.png)

**Comment by cxOrz** [comment]
邮件，回头闲了实现一下

**Comment by q2929843202** [comment]
> 右键卡片，删除用户
在edge下  右键不生效啊  只会弹出浏览器菜单 没有删除用户这个选项 是我的问题么？
![image](https://user-images.githubusercontent.com/97284858/187880934-f6da8b51-a648-4e77-af80-d63536866bf1.png)

**Comment by cxOrz** [comment]
![image](https://user-images.githubusercontent.com/32982052/187881176-c58051a6-2920-4e9a-9bd5-f215da124a84.png)
不太清楚，没用过edge浏览器。按理说和chrome一样，都是chromium开发的，应该表现也一样啊..

**Comment by q2929843202** [comment]
> ![图像](https://user-images.githubusercontent.com/32982052/187881176-c58051a6-2920-4e9a-9bd5-f215da124a84.png)不太清楚，没用过edge浏览器。按理说和chrome一样，都是铬开发的，应该表现也一样啊..

换了一下浏览器 确实可以了  就是edge的原因 这个移除弹不出来

**Comment by cxOrz** [comment]
https://github.com/cxOrz/chaoxing-sign-cli/commit/fd49520e68bf5f8db8414152ab1a44cdce8d0dd8 邮件通知
