### ISSUE TITLE
同一个设备部署cli和ui 成功ui显示监听，但是无法签到。

### ISSUE THREAD

**Issue by 418667527** [cxOrz/chaoxing-sign-cli#73]
cli监听实现签到 
ui监听无法签到。ui手动签到可以。
这是什么情况？

**Comment by cxOrz** [comment]
不清楚，试了下，ui监听自动签上了。

**Comment by cxOrz** [comment]
既然直接运行可以自动签，那ui也必能自动签上。

**Comment by 418667527** [comment]
我再试试吧

**Comment by 418667527** [comment]
感谢🙏

**Comment by 418667527** [comment]
> 既然直接运行可以自动签，那ui也必能自动签上。

换了服务器还是一样的，ui配置好了登录也没问题，但是监听没用，手动点里面的开始可以签到。
![无标题](https://user-images.githubusercontent.com/63603940/188316419-21cc2c0d-474d-4cdc-be53-bbdc897b5209.jpg)

**Comment by cxOrz** [comment]
加个q，细说

**Comment by 418667527** [comment]
> 加个q，细说

就是用户名

**Comment by cxOrz** [comment]
搜不到

**Comment by cxOrz** [comment]
是不是设置了权限

**Comment by 418667527** [comment]
权限开了 不好意思

**Comment by cxOrz** [comment]
https://github.com/cxOrz/chaoxing-sign-cli/commit/2e1c2bbe5af43b6fe6ed727bb968823ec7c6216c 大意了，已修 :(
