### ISSUE TITLE
pm2 怎么运行接口

### ISSUE THREAD

**Issue by qq357877431** [cxOrz/chaoxing-sign-cli#74]
每次关闭shell之后他就自动关闭了 

![微信图片_20220905094005](https://user-images.githubusercontent.com/47309681/188343875-77547cf5-d485-4a38-816d-63051f8e26c3.png)

**Comment by qq357877431** [comment]
> 每次关闭shell之后他就自动关闭了
> 
> ![微信图片_20220905094005](https://user-images.githubusercontent.com/47309681/188343875-77547cf5-d485-4a38-816d-63051f8e26c3.png)

开启pm2 之后执行这个

**Comment by cxOrz** [comment]
1. 安装依赖
2. 在chaoxing-sign-cli目录下，运行 `vim run.sh`，输入以下内容，保存
```bash
#!/bin/bash
NODE_OPTIONS="-r ts-node/register --no-warnings" node ./src/serve.ts
```
3. 添加执行权限 `chmod +x run.sh`
4. 运行 `pm2 start run.sh`

**Comment by qq357877431** [comment]
> 1. 安装依赖
> 2. 在chaoxing-sign-cli目录下，运行 `vim run.sh`，输入以下内容，保存
> 
> ```shell
> #!/bin/bash
> NODE_OPTIONS="-r ts-node/register --no-warnings" node ./src/serve.ts
> ```
> 
> 3. 添加执行权限 `chmod +x run.sh`
> 4. 运行 `pm2 start run.sh`

太感谢您了 谢谢谢谢
