### ISSUE TITLE
今天强制更新了一下 然后监听模式报错

### ISSUE THREAD

**Issue by q2929843202** [cxOrz/chaoxing-sign-cli#77]
然后UI那边一直在加载中无法启动监听模式
![image](https://user-images.githubusercontent.com/97284858/188855200-c9e4323e-4d89-4013-9690-6e16355b5d98.png)

我以为是监听配置出了问题
![image](https://user-images.githubusercontent.com/97284858/188855033-282c8e12-0c46-40f2-b343-29212739aa42.png)

启动了一下监听模式 然后发现报错

**Comment by cxOrz** [comment]
`npm install` 或者 `yarn` 安装依赖

**Comment by q2929843202** [comment]
> `npm install`或者 安装依赖`yarn`
OK已经解决

**Comment by sxceocom** [comment]
> > `npm install`或者 安装依赖
> > OK已经解决`yarn`

兄弟是依赖问题嘛
