### ISSUE TITLE
让 监听模式 支持读取本地的账号数据

### ISSUE THREAD

**Issue by pencilqaq** [cxOrz/chaoxing-sign-cli#79]
如题 monitor 模式不支持读取本地存储过的账号 请求添加支^.^

**Comment by cxOrz** [comment]
会随缘实现的，最近较忙~

**Comment by pencilqaq** [comment]
> 会随缘实现的，最近较忙~

 麻烦了 我也会抽空尝试做这个功能

**Comment by cxOrz** [comment]
https://github.com/cxOrz/chaoxing-sign-cli/commit/d91212487e1db9ebf4bdd1ba4f2579cb01ec5615 已实现
