### ISSUE TITLE
将拍照签到按普通签到

### ISSUE THREAD

**Issue by r27153733** [cxOrz/chaoxing-sign-cli#80]
将拍照签到按普通签到，教师那里是怎么显示的，一张黑图片吗？。

**Comment by cxOrz** [comment]
直接不会有照片

**Comment by r27153733** [comment]
> 直接不会有照片

我如果选no的话，是不是普通签到也不会签了。

**Comment by cxOrz** [comment]
如果no的话，就是所有普通签到都提交照片。无论是不是拍照，都会提交上去照片，可以看到。

**Comment by r27153733** [comment]
> 如果没有的话，就是所有普通签到都可以。

有没有考虑做一下区分。

**Comment by cxOrz** [comment]
这个无法区分

**Comment by cxOrz** [comment]
所以给出选项，让做出选择

**Comment by r27153733** [comment]
> 这个无法区分

https://github.com/moeshin/cx-auto-sign 这个项目可以区分，能否参考一下。
