### ISSUE TITLE
打卡成功后连发四封邮件

### ISSUE THREAD

**Issue by NANYUA** [cxOrz/chaoxing-sign-cli#81]
![image](https://user-images.githubusercontent.com/57891783/190102579-0c04a9ae-3be7-4474-a9e0-49d2ea6e513f.png)
这是怎么回事啊

**Comment by cxOrz** [comment]
是最新版本吗

**Comment by cxOrz** [comment]
可否把没打马赛克的版本发来看看

**Comment by cxOrz** [comment]
只发了一个签到对吗，没有其他任何活动，没任何消息吗

**Comment by NANYUA** [comment]
![image](https://user-images.githubusercontent.com/57891783/190109180-54afae63-35f3-4751-a95d-11f914368865.png)
对的，只有这一个签到

**Comment by NANYUA** [comment]
![image](https://user-images.githubusercontent.com/57891783/190109472-69ca927e-0fa6-4528-865d-ea81a433b50a.png)
而且每次刚好都是四个

**Comment by cxOrz** [comment]
奇怪。我这里试了，是一次没问题啊

**Comment by NANYUA** [comment]
可能是啥原因呢，我排查一下看看

**Comment by NANYUA** [comment]
![image](https://user-images.githubusercontent.com/57891783/190118148-9f8b64c3-47f0-4aa6-baad-090b71cae5fe.png)

**Comment by cxOrz** [comment]
看看为什么执行了多次sendMail函数

**Comment by cxOrz** [comment]
这是什么签到，普通还是什么，发下课程id，我加入看看

**Comment by NANYUA** [comment]
普通签到 12716948

**Comment by cxOrz** [comment]
解除禁言下

**Comment by NANYUA** [comment]
救命啊大佬，还是四封邮件

**Comment by moeshin** [comment]
做个缓存吧

**Comment by cxOrz** [comment]
亲测无问题，可能是开了多个监听进程
