### ISSUE TITLE
二维码签到失效

### ISSUE THREAD

**Issue by 9527-bit** [cxOrz/chaoxing-sign-cli#82]

**Comment by cxOrz** [comment]
一切正常

**Comment by 9527-bit** [comment]
那我去检查一下配置

**Comment by cxOrz** [comment]
开始了。我也不正常了。我去看看为啥

**Comment by 9527-bit** [comment]
> 开始了。我也不正常了。我去看看为啥

好像是今天才失效的，现在用微信扫一扫会直接跳超星那边去，不像以前的出那串码

**Comment by cxOrz** [comment]
看了下链接变了，回头看看能不能解决

**Comment by cxOrz** [comment]
可以用了现在，更新仓库

**Comment by 9527-bit** [comment]
> 可以用了现在，更新仓库

好像还是失败的，我用你的演示站也没成

**Comment by cxOrz** [comment]
网站，本来就是个界面展示。代码基本不更新。

**Comment by cxOrz** [comment]
顺带一提。俩仓库都得更新

**Comment by cxOrz** [comment]
再顺带一提，代码变更后，得重新build。这个在readme里提到过~

**Comment by 9527-bit** [comment]
> 再顺带一提，代码变更后，得重新build。这个在readme里提到过~

懂👌现在正常运行了
