### ISSUE TITLE
配置邮箱后签到收不到邮件通知

### ISSUE THREAD

**Issue by NANYUA** [cxOrz/chaoxing-sign-cli#83]
问题宝宝来了，配置好好了监听的邮件通知可是签到成功后无邮件提醒

**Comment by cxOrz** [comment]
检查检查，看看是不是密码错误，还是邮箱写错了，SSL开不？端口写对没？之前能发现在却发不了。

**Comment by cxOrz** [comment]
要看你提供邮箱那边，人家要求的配置了。我这是465

**Comment by NANYUA** [comment]
主要是我这边一直是默认，现在不行了

**Comment by cxOrz** [comment]
再仔细检查检查吧🥹

**Comment by NANYUA** [comment]
签到签上了但是没邮件提醒只能是因为这几个问题对吧

**Comment by cxOrz** [comment]
也不一定。也可能是配置没生效。记得变更代码后，重新build

**Comment by NANYUA** [comment]
配置文件不是在build文件夹里吗，build以后就恢复默认了诶

**Comment by cxOrz** [comment]
配置文件不在build文件夹，不要修改build文件夹的任何内容。

**Comment by NANYUA** [comment]
那配置文件只能运行pum run monitor以后改吗

**Comment by cxOrz** [comment]
啥时候都可以改，默认能配置的也就是那个env.json。
最重要的是，任何变更，都要重新build就行

**Comment by NANYUA** [comment]
邮件账号 … QQ号@qq.com
授权码(密码) … 邮箱密码
接收邮箱 … QQ号@qq.com

**Comment by NANYUA** [comment]
是这样写的吗

**Comment by cxOrz** [comment]
是的。授权码是从QQ邮箱那里生成的，注意不是QQ密码。睡觉了先

**Comment by cxOrz** [comment]
整出来了吗

**Comment by NANYUA** [comment]
整出来了，好像是授权码前面有个空格的样子，我删了就有了。然后我发现我ui界面打开监听就会发两封邮件，关了就正常了
