### ISSUE TITLE
登录失败，安卓termux（上学期正常，今天登录后这样，已更新）

### ISSUE THREAD

**Issue by Meteorsss** [cxOrz/chaoxing-sign-cli#84]
登陆失败
正在检查更新，若等待时间过长请挂代理...(连按 Ctrl+C 终止)
Updating cd0cdcd..f76812e
error: Your local changes to the following files would be overwritten by merge:
        src/configs/storage.json
Please commit your changes or stash them before you merge.
Aborting
（上学期正常，今天登录后这样，已更新）

**Comment by cxOrz** [comment]
显然，没更新成功。

强制更新 
```bash
git fetch
git reset --hard origin/main
```

要是还不行，改个密码，再试。

**Comment by cxOrz** [comment]
整出来了吗
