### ISSUE TITLE
PM2怎么自动监听啊大佬，UI点了登录没反应

### ISSUE THREAD

**Issue by ttthhhhnmmmm** [cxOrz/chaoxing-sign-cli#86]
PM能自动开接口，但是自动监听我不会弄，他永远卡在用户名那里，不能下一步
![image](https://user-images.githubusercontent.com/112688590/191398581-7775dba9-1e51-4781-b67b-96186195feba.png)
UI界面登录没反应，sign-ui里面IP是3000.cil里面ip是5000，ui里面我改了自己的域名也不行，登录不上

**Comment by cxOrz** [comment]
PM2 是让守护接口进程的，build完之后运行接口
```bash
pm2 start build/serve.js
```

点登录没反应，就F12看看网络请求有什么错误

**Comment by cxOrz** [comment]
只运行监听的话，不用 PM2，直接 `npm run monitor` 挂着就行了

**Comment by ttthhhhnmmmm** [comment]
监听能设置开机自启吗

**Comment by ttthhhhnmmmm** [comment]
![image](https://user-images.githubusercontent.com/112688590/191627759-a8072ec8-03b2-4617-a8d5-e960eb9d4e03.png)

**Comment by cxOrz** [comment]
你这个域名怎么还带空格
![image](https://user-images.githubusercontent.com/32982052/191652623-574d7a09-d61f-44ec-bd6d-5047e163d89c.png)

**Comment by cxOrz** [comment]
> 监听能设置开机自启吗

用 cron 来 diy

**Comment by ttthhhhnmmmm** [comment]
> 你这个域名怎么还带空格 ![image](https://user-images.githubusercontent.com/32982052/191652623-574d7a09-d61f-44ec-bd6d-5047e163d89c.png)

大佬我弄好了，但是自动监听没用呀，可以查到但是不能自动签到
![image](https://user-images.githubusercontent.com/112688590/191653183-d0574eb9-21fc-4ea5-916e-61c63abcce4a.png)

**Comment by cxOrz** [comment]
二维码不能自动，其他的可以

**Comment by ttthhhhnmmmm** [comment]
然后每次点监听会弹出来一个窗口
![image](https://user-images.githubusercontent.com/112688590/191653775-89ecae7f-9646-4e99-b4e7-5f51d34a4ae7.png)

**Comment by cxOrz** [comment]
事先运行 `npm run monitor` 配置好签到信息，看到 [监听中] 信息就存好了，就可以关掉了，然后运行 `npm run build` 构建一下，让变更生效。之后就可以 `npm run serve`  重新运行接口。

**Comment by cxOrz** [comment]
> 然后每次点监听会弹出来一个窗口 ![image](https://user-images.githubusercontent.com/112688590/191653775-89ecae7f-9646-4e99-b4e7-5f51d34a4ae7.png)

这我也不知道为啥，我这边没弹出过...

**Comment by ttthhhhnmmmm** [comment]
> > 然后每次点监听会弹出来一个窗口 ![image](https://user-images.githubusercontent.com/112688590/191653775-89ecae7f-9646-4e99-b4e7-5f51d34a4ae7.png)
> 
> 这我也不知道为啥，我这边没弹出过...

实测这个窗口关了就不能监听，开着就 可以，好奇怪

**Comment by cxOrz** [comment]
你是在哪运行的命令

**Comment by ttthhhhnmmmm** [comment]
> 你是在哪运行的命令

cmd运行的命令

**Comment by cxOrz** [comment]
试了一下，Windows 下用 cmd、powershell 都不弹，Linux 更不弹。我也不太清楚你那里为什么会弹窗口。不过不影响，忽略他吧

**Comment by ttthhhhnmmmm** [comment]
> 试了一下，Windows 下用 cmd、powershell 都不弹，Linux 更不弹。我也不太清楚你那里为什么会弹窗口。不过不影响，忽略他吧

登录一个用户弹一个窗口

**Comment by cxOrz** [comment]
更新一下代码 `git pull`
然后 重新构建一下，再运行试试看？
我不知道添加了个 detached: false 能不能解决，这个问题从未见过。

**Comment by ttthhhhnmmmm** [comment]
> 更新一下代码 `git pull` 然后 重新构建一下，再运行试试看？ 我不知道添加了个 detached: false 能不能解决，这个问题从未见过。

大佬试过了，还是不行

**Comment by ttthhhhnmmmm** [comment]
> > 更新一下代码 `git pull` 然后 重新构建一下，再运行试试看？ 我不知道添加了个 detached: false 能不能解决，这个问题从未见过。
> 
> 大佬试过了，还是不行

有没有可能跟我监听的设置有关系，位置，邮箱之内的？

**Comment by ttthhhhnmmmm** [comment]
> 更新一下代码 `git pull` 然后 重新构建一下，再运行试试看？ 我不知道添加了个 detached: false 能不能解决，这个问题从未见过。

或者是我用PM2的方法不对，应该怎么使用PM2挂接口呢大佬
