### ISSUE TITLE
不知道为什么在手机上位置签到会报错

### ISSUE THREAD

**Issue by truthNihilism** [cxOrz/chaoxing-sign-cli#87]
手机端输入了教室所在的经度与纬度和详细的地址,但是不知道为什么会显示不在签到的范围内,有时候还会报错.

**Comment by truthNihilism** [comment]
![Screenshot_2022-09-21-14-33-43-95_84d3000e3f40171](https://user-images.githubusercontent.com/111174715/191664818-b05f0674-fbc1-48b3-8dfd-0193f0e49521.jpg)

**Comment by truthNihilism** [comment]
![Screenshot_2022-09-21-14-28-25-95_84d3000e3f40171(1)](https://user-images.githubusercontent.com/111174715/191665018-116f4b86-bc21-4650-9777-171ccb37eea6.png)

**Comment by cxOrz** [comment]
不在可签到范围：经纬度位置不在限定范围内

**Comment by cxOrz** [comment]
我试试看

**Comment by cxOrz** [comment]
试了下，限制范围300米内，成功。那估计是你位置没填准。
![IMG20220922194635](https://user-images.githubusercontent.com/32982052/191738560-f9d1a20b-3ffc-4932-bee3-49f7b804aed1.jpg)

**Comment by truthNihilism** [comment]
现在好了，就是位置没有填准。
