### ISSUE TITLE
建议 增加更多接口通知推送 增加签到延时

### ISSUE THREAD

**Issue by yanhy2000** [cxOrz/chaoxing-sign-cli#88]
我之前将项目部署后发现没及时推送的方式(邮箱除外)，如签到失败时无法及时发现或者不能知晓签到状态,因此我自己接入了pushplus微信推送，推送方式为get请求：

``` https.get(`https://www.pushplus.plus/send?token=${pushplus_key}&title=cx-签到通知√&content=${str.toString()}\`, (res) => {
console.log("pushplus推送完成，状态码：",res.statusCode)
}) ```

收到推送内容大致为：
```
xx年月日时间
检测到活动：签到码签到测试 活动id：5
已获取签到码：1315
【通用】签到成功，随机延时:xxxx ms
```

由于本人技术不高，代码不规范，因此仅提出建议，就不提出pr申请了，也希望能新增一些便捷的推送方式。我自己大概是新增了，随机延时4-10秒签到、pushplus推送、从获取的res中正则获取签到码手势码、定时崩溃(由自己写的守护拉起)，以及零零散散的东西，因为是自用，所以没引出配置文件，也没规范代码

感谢这个项目，为我日常的大学生活提供一些便利

**Comment by cxOrz** [comment]
邮件我感觉已经满足通知的需求了。签到成功或者失败，都会发到我绑的QQ邮箱，微信和QQ都会来消息提示邮件，可以看到签到信息、成功还是失败。延时确实需要，待会加上。

**Comment by cxOrz** [comment]
6bdd7bf8cf007a756f00863ec9ed1f6489b5df20 增加签到延时

**Comment by cxOrz** [comment]
pushplus 这样的个性化的需求，还是DIY最合适

**Comment by yanhy2000** [comment]
收到

**Comment by ZhangEmo** [comment]
大佬 请教一下DIY推送怎么配置的

**Comment by cxOrz** [comment]
这我也不知道…我甚至没听说过bark是什么

**Comment by yanhy2000** [comment]
> 大佬请教一下DIY怎么配置的

取决于推送通道的推送方法，比如我用的pushplus，仅需申请token后进行get请求，即可实现推送，因此只需要在签到结果那边添加个get请求加自己的内容就可以实现推送

**Comment by ZhangEmo** [comment]
> > 大佬请教一下DIY怎么配置的
> 
> 取决于推送通道的推送方法，比如我用的pushplus，仅需申请token后进行get请求，即可实现推送，因此只需要在签到结果那边添加个get请求加自己的内容就可以实现推送

纯小白 不知道加在哪 55
