### ISSUE TITLE
关于 moniter 模式

### ISSUE THREAD

**Issue by Rylanwe** [cxOrz/chaoxing-sign-cli#89]
首先感谢作者开源，我想请问一下为什么建议监听模式”每次需要时启用2-4小时较为合适，请勿挂着不关。“，是学习通会有什么检测吗？

**Comment by cxOrz** [comment]
因为挂着就类似于打开了学习通的网页版聊天功能，会和服务器保持一个Websocket连接，没有人会一直在聊天页面一直待一天甚至几天。我觉得容易引起怀疑，所以保险起见不要挂着不关。
