### ISSUE TITLE
坐姿 您好 请问安装好了node还这个样子怎么办

### ISSUE THREAD

**Issue by 857857-lps** [cxOrz/chaoxing-sign-cli#90]
![527ae32a84676919138baf9c9eb27b7](https://user-images.githubusercontent.com/84233556/192114807-260cce23-401e-4c36-bf40-b9e1c4784564.jpg)

**Comment by cxOrz** [comment]
node是安装好了，但是没看到项目在哪

**Comment by cxOrz** [comment]
![Screenshot_20220925-110450_Chrome](https://user-images.githubusercontent.com/32982052/192126370-01b897d0-21e7-4ca8-a0e4-773a1f277295.png)

**Comment by 857857-lps** [comment]
不好意思作者 我小白 这个我输入之后显示这样 安装依赖这一步好像没有成功
![c91213bffee05f9f96998a3e7f7dab2](https://user-images.githubusercontent.com/84233556/192128363-7900a1c9-190c-4f86-a9f7-59fa50874bd3.jpg)
麻烦解答

**Comment by cxOrz** [comment]
网络问题，慢慢等或者，挂全局代理

**Comment by 857857-lps** [comment]
现在安装好了也可以运行了 就是每次退出termux程序都要重新运行这个cd chaoxing-sign-cli
npm install才能使用  请问是我什么地方出问题了吗

**Comment by cxOrz** [comment]
每次就是得cd到目录，然后npm run start或者别的

**Comment by 857857-lps** [comment]
谢谢解答
