### ISSUE TITLE
昨天多了个“ 增加延时签到功能”但是版本号和介绍里都没提

### ISSUE THREAD

**Issue by key-destroyer** [cxOrz/chaoxing-sign-cli#91]
延时签到功能现在在监听模式里可以用了吗![J4M4_ (MR4P{JI $6JRCMFR](https://user-images.githubusercontent.com/95562662/192130444-71f1287e-b91a-4e9f-b57b-db381d848c41.png)

**Comment by cxOrz** [comment]
更新一下，然后build一下，运行monitor，重新配置就能看到延时选项，默认是0秒。

**Comment by key-destroyer** [comment]
明白了 谢谢
