### ISSUE TITLE
大佬可否加入其他推送渠道？

### ISSUE THREAD

**Issue by ZhangEmo** [cxOrz/chaoxing-sign-cli#92]
大佬会不会考虑加入其他推送渠道 想bark推送但是不会自己DIY

**Comment by cxOrz** [comment]
只支持邮件通知，可以用QQ邮箱，会在微信和QQ里都推送。其他推送不会支持，只支持大众化的需求，还是看看怎么DIY吧

**Comment by ZhangEmo** [comment]
好的 我再想想办法
