### ISSUE TITLE
大佬，看看这个api是不是可以拿到enc

### ISSUE THREAD

**Issue by xbn2002** [cxOrz/chaoxing-sign-cli#93]
我找到了一个好像能获取二维码签到enc的api，但是没有测试的签到可以用来试，麻烦大佬帮忙看看是否有效：
https://mobilelearn.chaoxing.com/v2/apis/sign/refreshQRCode?activeId=
其中activeId指的是签到活动的ID，可以通过访问课程的活动列表获取到。

**Comment by xbn2002** [comment]
好像无效了，提示无权限获取

**Comment by cxOrz** [comment]
这个我试过，这是以签到发布者的身份才可以获取的。其他人无权
