### ISSUE TITLE
邮件通知只能发送给一个人

### ISSUE THREAD

**Issue by NANYUA** [cxOrz/chaoxing-sign-cli#95]
和同学一起用的，监听签到成功的邮件通知只能发送给一个人的邮箱吗，可以登陆的时候选择发送邮箱吗？能放在ui登陆的时候输入就更好了，感谢大佬

**Comment by cxOrz** [comment]
这个我也有打算调整一下，每个用户有一份自己的配置。日后闲了调整一下

**Comment by NANYUA** [comment]
好的，谢谢大佬了

**Comment by cxOrz** [comment]
172c5e61cb5b43e54b138b5a5146fd4573355368 试一下

每个用户一份配置，仍然和以前一样的使用方法，只不过配置三个用户的信息的话，就是运行三次  `yarn monitor` 分别登录配置三个用户的签到/邮件信息。

**Comment by cxOrz** [comment]
如果没有经过服务器主人的配置，点击监听不会启动，并提示未配置。
![image](https://user-images.githubusercontent.com/32982052/194377983-5ee97f86-7d0e-4110-8184-a2349bc4c4d2.png)

小众程序，不打算做客户端配置用户的签到信息了，一切由服务器主人配置。 我自己部署的给朋友用用，说好不分享给更多人，还是被乱分享了，每天都有一堆不认识的人签到。

不在服务器配置无法在UI页面监听，其他正常~

**Comment by cxOrz** [comment]
是的
