### ISSUE TITLE
二维码有自动获取的解决办法或者思路不？有个网站可以“盲签”，应该是能获取到的

### ISSUE THREAD

**Issue by Trump-Shuai** [cxOrz/chaoxing-sign-cli#96]

**Comment by cxOrz** [comment]
二维码没有办法，只能找人拍

**Comment by toutwoa** [comment]
> 

以前有个网站是 http://xn--rcrv02h.xn--6cs.top/login.html 他可以支持盲签无需拍照，但是停止运行了，不知道是怎么做到的

**Comment by cxOrz** [comment]
二维码从教师端生成，使用教师的身份凭证才能访问，其他的会返回“无权访问”。如果他可以绕过学习通服务器的权限检测，那确实可以。不过没代码，我也不知道是怎么实现的
