### ISSUE TITLE
OCR巨慢

### ISSUE THREAD

**Issue by toutwoa** [cxOrz/chaoxing-sign-cli#98]
可以支持别家的OCR吗？或者是我的网太拉了？所有地区都是15秒左右，图片是相机直出，2.9M，大伙OCR速度怎么样呢？
![image](https://user-images.githubusercontent.com/87063575/192747732-62d623a7-bac5-4acc-bdf8-477621f32909.png)

**Comment by cxOrz** [comment]
应该是你的网太拉了

**Comment by cxOrz** [comment]
腾讯的OCR又快又准，一直在用

**Comment by toutwoa** [comment]
> 腾讯的OCR又快又准，一直在用

会不会是图片太大的问题，1M以下确实是又快又准，相机直出的话都2M多，就会非常慢。

**Comment by cxOrz** [comment]
有可能，毕竟传输会慢，像素太多，解析起来更慢。
